import { Language, TranslationSet, Location, LocationData, WifiSpot } from "./types";

export const TUZLA_CENTER: [number, number] = [44.5388, 18.6750];

const LOCATIONS_RAW: Location[] = [
  {
    id: '1',
    name: {
      en: 'Pannonian Lakes',
      bs: 'Panonska jezera',
      de: 'Panonische Seen',
      tr: 'Pannonian Gölleri',
    },
    description: {
      en: 'The only salt lakes in Europe located in the city center. A unique complex of three lakes with medicinal properties.',
      bs: 'Jedina slana jezera u Evropi u centru grada. Jedinstven kompleks tri jezera sa ljekovitim svojstvima.',
      de: 'Die einzigen Salzseen in Europa direkt im Stadtzentrum. Einzigartiger Komplex aus drei Seen mit heilender Wirkung.',
      tr: 'Şehir merkezinde bulunan Avrupa\'nın tek tuz gölleri. Tıbbi özelliklere sahip üç gölden oluşan eşsiz bir kompleks.',
    },
    image: '/assets/Gallery/QuestQRLocations/Panonsko jezero.png',
    coordinates: [44.5385, 18.6767],
    category: 'nature',
    qrCode: 'Pannonian Lakes',
    discount: '10%',
  },

  {
    id: '3',
    name: {
      en: 'Salt Square',
      bs: 'Trg soli',
      de: 'Salzplatz',
      tr: 'Tuz Meydanı',
    },
    description: {
      en: 'A square celebrating Tuzla s 2,500-year salt history with a replica salt well.',
      bs: 'Trg posvecen tuzlanskoj 2.500 godina dugoj historiji proizvodnje soli, sa replikom bunara za so.',
      de: 'Ein Platz, der Tuzlas 2.500-jahrige Geschichte der Salzgewinnung feiert, inklusive einer Replik eines Salzbrunnens.',
      tr: 'Tuzla\'nın 2.500 yıllık tuz tarihini bir tuz kuyusu kopyasıyla kutlayan bir meydan.',
    },
    image: '/assets/Gallery/QuestQRLocations/sonitrg.webp',
    coordinates: [44.5382182, 18.6759398],
    category: 'culture',
    qrCode: 'QRsonitrg',
    discount: 5,
    address: 'Solni trg, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: 'kapija',
    name: {
      en: 'Kapija',
      bs: 'Kapija',
      de: 'Kapija',
      tr: 'Kapija',
    },
    description: {
      en: 'Historical monument and memorial square in the center of Tuzla.',
      bs: 'Historijski spomenik i trg u samom centru Tuzle.',
      de: 'Historisches Denkmal und Platz im Zentrum von Tuzla.',
      tr: 'Tuzla şehir merkezindeki tarihi anıt ve meydan.',
    },
    image: '/assets/Gallery/QuestQRLocations/kapija.webp',
    coordinates: [44.53863, 18.676805],
    category: 'culture',
    qrCode: 'QRkapija',
    discount: 'Special Reward',
    address: 'Trg Kapija, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: '5',
    name: {
      en: 'Tuzlanka Mall',
      bs: 'RK Tuzlanka',
      de: 'Tuzlanka Einkaufszentrum',
      tr: 'Tuzlanka Alışveriş Merkezi',
    },
    description: {
      en: 'One of the city s main shopping destinations with a variety of international and local brands.',
      bs: 'Jedna od glavnih shopping destinacija u gradu sa raznim medjunarodnim i lokalnim brendovima.',
      de: 'Eines der wichtigsten Einkaufsziele der Stadt mit vielen internationalen und lokalen Marken.',
      tr: 'Çeşitli uluslararası ve yerel markaların bulunduğu şehrin ana alışveriş noktalarından biri.',
    },
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=400',
    coordinates: [44.5381, 18.6650],
    category: 'shopping',
    qrCode: 'Tuzlanka Mall',
    discount: 10,
  },
  {
    id: 'mesa_selimovic',
    name: {
      en: 'Mesa Selimovic Statue',
      bs: 'Kip Meše Selimovića',
      de: 'Mesa-Selimovic-Statue',
      tr: 'Meşa Selimoviç Heykeli',
    },
    description: {
      en: 'Statue of the famous writer Mesa Selimovic.',
      bs: 'Kip poznatog pisca Meše Selimovica.',
      de: 'Statue des beruehmten Schriftstellers Mesa Selimovic.',
      tr: 'Ünlü yazar Meşa Selimoviç\'in heykeli.',
    },
    image: '/assets/Gallery/mesaselimovic.webp',
    coordinates: [44.5370993, 18.6781216],
    category: 'culture',
    qrCode: 'Mesa Selimovic',
    discount: 'Video Reward',
  },
  {
    id: 'tvrtko_park',
    name: {
      en: 'King Tvrtko Park',
      bs: 'Park Kralja Tvrtka I',
      de: 'Koenig-Tvrtko-Park',
      tr: 'Kral Tvrtko Parkı',
    },
    description: {
      en: 'Central City Park featuring the monument of King Tvrtko I, the first Bosnian king.',
      bs: 'Centralni gradski park sa spomenikom Kralju Tvrtku I, prvom bosanskom kralju.',
      de: 'Zentraler Stadtpark mit dem Denkmal von Koenig Tvrtko I., dem ersten bosnischen Koenig.',
      tr: 'Bosna\'nın ilk kralı olan I. Kral Tvrtko\'nun anıtının bulunduğu merkezi şehir parkı.',
    },
    image: '/assets/Gallery/QuestQRLocations/Tvrko pannellum/KraljTvrko11.webp',
    coordinates: [44.5380826, 18.6783327],
    category: 'culture',
    qrCode: 'King Tvrtko',
    discount: 'Virtual Discovery',
  },
  {
    id: 'bingo_city_centar',
    name: {
      en: 'Bingo City Center',
      bs: 'Bingo City Centar',
      de: 'Bingo City Einkaufszentrum',
      tr: 'Bingo City Alışveriş Merkezi',
    },
    description: {
      en: 'The largest shopping mall in the region with numerous stores, cinemas, and entertainment options.',
      bs: 'Najveći tržni centar u regiji sa brojnim trgovinama, kinom i zabavnim sadržajima.',
      de: 'Das größte Einkaufszentrum der Region mit zahlreichen Geschäften, Kinos und Unterhaltungsangeboten.',
      tr: 'Bölgenin çok sayıda mağaza, sinema ve eğlence seçeneği sunan en büyük alışveriş merkezi.',
    },
    image: '/assets/Gallery/QuestQRLocations/Bingo City Centar.png',
    coordinates: [44.532177, 18.651743],
    category: 'culture',
    qrCode: 'Bingo City Centar',
    discount: 'Special Rewards',
    website: 'https://tuzla.bingocitycenter.ba/',
  },
  {
    id: 'atelje_ismet',
    name: {
      en: 'Atelje Ismet Mujezinovic',
      bs: 'Atelje Ismet Mujezinović',
      de: 'Ismet Mujezinovic Atelier',
      tr: 'Ismet Mujezinovic Atölyesi',
    },
    description: {
      en: 'The former studio and gallery of the famous Bosnian painter Ismet Mujezinović.',
      bs: 'Bivši atelje i galerija poznatog bosanskog slikara Ismeta Mujezinovića.',
      de: 'Das ehemalige Atelier und die Galerie des berühmten bosnischen Malers Ismet Mujezinović.',
      tr: 'Ünlü Bosnalı ressam Ismet Mujezinović\'in eski atölyesi ve galerisi.',
    },
    image: '/assets/Gallery/QuestQRLocations/Atelje Ismet Mujezinovic.png',
    coordinates: [44.5371465, 18.6810454],
    category: 'culture',
    qrCode: 'Atelje Ismet Mujezinovic',
    discount: 'Art Reward',
    address: 'Klosterska 19, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: 'slana_banja',
    name: {
      en: 'Slana Banja Park',
      bs: 'Slana Banja',
      de: 'Slana Banja Park',
      tr: 'Slana Banja Parkı',
    },
    description: {
      en: 'A memorial park and recreational area with beautiful walk paths and historical monuments.',
      bs: 'Memorijalni park i rekreaciona zona sa prelijepim stazama i historijskim spomenicima.',
      de: 'Ein Gedenkpark und Erholungsgebiet mit schönen Wanderwegen und historischen Denkmälern.',
      tr: 'Güzel yürüyüş yolları ve tarihi anıtların bulunduğu bir anıt parkı og dinlenme alanı.',
    },
    image: '/assets/Gallery/QuestQRLocations/QR Banja.png',
    coordinates: [44.5378167, 18.6875664],
    category: 'nature',
    qrCode: 'QR Banja',
    discount: 'Health Reward',
    address: 'Park Slana Banja, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: 'Palancinkara Bagi',
    name: {
      en: 'Pancake Bagi',
      bs: 'Palančikara Bagi',
      de: 'Pancake Bagi',
      tr: 'Pancake Bagi',
    },
    description: {
      en: 'A famous dessert spot in Tuzla, known for its creative sweet pancakes and pancake sushi.',
      bs: 'Poznato mjesto za deserte u Tuzli, poznato po kreativnim slatkim palačinkama i sushi palačinkama.',
      de: 'Ein berühmtes Dessert-Lokal in Tuzla, bekannt für seine kreativen süßen Pfannkuchen und Pancake-Sushi.',
      tr: 'Tuzla\'da yaratıcı tatlı krepleri ve krep suşileriyle tanınan ünlü bir tatlı noktası.',
    },
    image: '/assets/Gallery/Food/bagi.webp',
    coordinates: [44.5383762, 18.6775339],
    category: 'culture',
    qrCode: 'Palancinkara Bagi',
    discount: 'Sweet Reward',
    address: 'Trg Kapija, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: 'slapovi',
    name: {
      en: 'Waterfalls',
      bs: 'Slani Vodopadi Panonskih Jezera',
      de: 'Salzwasserfälle',
      tr: 'Tuz Şelaleleri',
    },
    description: {
      en: 'Beautiful saline waterfalls within the Pannonian Lakes complex, offering therapeutic aerosol inhalation.',
      bs: 'Prelijepi slani vodopadi u sklopu kompleksa Panonskih jezera, koji nude terapeutsku inhalaciju aerosolom.',
      de: 'Wunderschöne Salz-Wasserfälle im Pannonischen Seenkomplex, die therapeutische Aerosolinhalationen bieten.',
      tr: 'Pannonian Gölleri kompleksindeki terapötik aerosol inhalasyonu sunan güzel tuz şelaleleri.',
    },
    image: '/assets/Gallery/QuestQRLocations/tzslapovi.webp',
    coordinates: [44.5404243, 18.6819408],
    category: 'nature',
    qrCode: 'QRslapovi',
    discount: 'Nature Reward',
    address: 'Pavkuša, 75000 Tuzla, Bosnia and Herzegovina',
  },
  {
    id: 'trg_slobode',
    name: {
      en: 'Freedom Square',
      bs: 'Trg slobode',
      de: 'Freiheitsplatz',
      tr: 'Özgürlük Meydanı',
    },
    description: {
      en: 'Freedom Square is the largest square in Bosnia and Herzegovina, featuring a beautiful fountain and historical buildings.',
      bs: 'Trg slobode je najveći trg u Bosni i Hercegovini, sa prekrasnom fontanom i historijskim zgradama.',
      de: 'Der Freiheitsplatz ist der größte Platz in Bosnien und Herzegowina mit einem schönen Brunnen und historischen Gebäuden.',
      tr: 'Bosna Hersek\'in en büyük meydanı olan Özgürlük Meydanı, güzel bir fıskiye ve tarihi binalara ev sahipliği yapmaktadır.',
    },
    image: '/assets/Gallery/QuestQRLocations/trgslobode.webp',
    coordinates: [44.53951751260547, 18.67490372669647],
    category: 'culture',
    qrCode: 'QRTrgSlobode',
    discount: 'Special Reward',
    address: 'Trg slobode, 75000 Tuzla, Bosnia and Herzegovina',
  }
];

const BINGO_STORE_RAW = {
  name: 'Bingo Supermarket',
  address: 'Mitra Trifunovica Uce 2, Tuzla',
  rating: '100%',
  hours: {
    en: { monSat: '08:00 - 20:30', sun: 'Closed' },
    bs: { monSat: '08:00 - 20:30', sun: 'Zatvoreno' },
    de: { monSat: '08:00 - 20:30', sun: 'Geschlossen' },
    tr: { monSat: '08:00 - 20:30', sun: 'Kapalı' },
  },
  items: [
    { name: 'Fresh Fruit', price: 'Varies', image: '/assets/Gallery/Fruit.webp' },
    { name: 'Quality Meat', price: 'Varies', image: '/assets/Gallery/Meat.webp' },
    { name: 'Charcuterie', price: 'Varies', image: '/assets/Gallery/Charcuterie.webp' },
    { name: 'Vegetables & Herbs', price: 'Varies', image: '/assets/Gallery/Vegetables___Herbs.webp' },
  ],
};



const TRANSLATIONS_RAW: Record<Language, TranslationSet> = {
  en: {
    welcome: 'Welcome to Tuzla',
    history: 'History',
    map: 'Map',
    quest: 'Quest',
    gallery: 'Gallery',
    scanQr: 'Scan QR Code',
    rewardClaimed: 'Reward Unlocked!',
    discountMessage: 'You received a discount! Show this at the counter.',
    notificationTitle: 'Special Offer!',
    notificationBody: 'Pannonian Lakes price is now 5 EUR instead of 6 EUR today!',
    close: 'Close',
    viewOnMap: 'View on Map',
    foundAt: 'Found at',
    liveEvents: 'Live Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login with OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Emergency Info',
    bestSupermarket: 'Supermarket',
    workingHours: 'Working Hours',
    monSat: 'Mon - Sat',
    sunday: 'Sunday',
    closed: 'Closed',
    rating: 'Rating',
    reviews: 'Reviews',
    delivery: 'Delivery Available',
    noDelivery: 'No Delivery',
    typicalPrice: 'Typical Price',
    arGuide: 'AR Guide',
    walletManual: 'User Manual',
    howToConnect: 'How to Connect',
    connectSteps: "1. Click 'Connect Wallet'\n2. Choose a TON wallet (Tonkeeper/Telegram)\n3. Confirm in your app",
    safeUsage: 'Safe Usage',
    safeTips: '. Never share your seed phrase\n. Confirm every transaction\n. Use official TON apps only',
    txHistory: 'Where is history?',
    historyLocation: 'Transaction history is saved within your connected TON wallet app.',
    bamToEur: 'BAM - EUR Conversion',
    enterBam: 'Enter amount in BAM',
    calculatedEur: 'Equivalent in EUR',
    conversionRate: 'Rate: 1 BAM = 0.51 EUR (1:1.95583)',
    pannonicaAlt: 'Pannonica Lakes - Salt Lakes in Tuzla',
    pannonicaTitle: 'Welcome to Pannonica',
    pannonicaImage: '/assets/Pannonica.webp',
    trademarksDisclaimer: 'All logos and brand names are properties of their respective owners and are used here for informational/identification purposes only.',
    privacyNoticeTitle: 'Privacy & Camera Notice',
    privacyNoticeBody: 'This app uses your location solely for navigation to points of interest. The camera is activated only when you are within 10m of a destination to scan a QR code and trigger the AR guide. Your images and video feed are not stored or sent to any server; all processing occurs strictly on your device. By continuing, you consent to temporary access to these functions.',
    learnMore: 'Learn More',
    busStation: 'Bus Station',
    batteryWarning: 'Extreme Battery Saver Active. Lower brightness and use AR only when moving to preserve power.',
    selectNetwork: 'Select Network',
    solWallet: 'Solana Wallet',
    switchNetwork: 'Switch Network',
    connectedToSol: 'Connected to Solana',
    walletLocked: 'Wallet Locked',
    setWalletPin: 'Set Wallet PIN',
    confirmPin: 'Confirm PIN',
    enterPin: 'Enter PIN to Unlock',
    dentalTourism: 'Dental Tourism',
    locationNotAvailable: 'Location not available.',
    zonesLabel: 'Zones',
    galleryCharmText: 'No photo can show you charm and beauty of this city, so come and visit us.',
    digitalWalletTitle: 'Digital Wallet',
    solanaConnection: 'Solana Connection',
    walletAddress: 'Wallet Address',
    statusNotConnected: 'Not connected',
    viewOnSolanaExplorer: 'View on Solana Explorer',
    explorationTitle: 'Exploration',
    qrLocationScannerTitle: 'QR Location Scanner',
    startScanner: 'Scan QR',
    qrScannerDesc: 'Find and scan QR codes at historical locations around Tuzla to unlock guide rewards and record them in your scan ledger.',
    currencyConverterTitle: 'Currency Converter',
    enterBamLabel: 'Enter BAM (KM)',
    enterEurLabel: 'Enter EUR (€)',
    estimatedEurLabel: 'Estimated EUR',
    estimatedBamLabel: 'Estimated BAM',
    conversionRateText: 'Rate: 1 EUR = 1.95583 BAM',
    scanHistoryLedgerTitle: 'Scan History Ledger',
    ledgerEmptyTitle: 'Ledger is empty',
    ledgerEmptyDesc: 'Scan location QR codes around the city to build your history.',
    clearScanHistory: 'Clear Scan History',
    clearHistoryConfirm: 'Are you sure?',
    yesDelete: 'Yes, delete',
    cancel: 'Cancel',
    partnerAgenciesTitle: 'Partner Agencies',
    scanLocationToUnlock: 'Scan location QR code to unlock',
    positionCodeInFrame: 'Position code within the frame',
    success: 'Success',
    error: 'Error',
    alreadyInLedger: 'is already in your ledger.',
    unlockedLocation: 'Unlocked location:',
    unknownQrCode: 'Unknown location QR code.',
    couldNotStartCamera: 'Could not start camera.',
    privacyDisclaimerText: 'This application functions as a non-custodial, self-sovereign interface. We provide the tools for you to interact with information and blockchain services, but you maintain absolute ownership and control of your digital assets and identity.',
    privacyKeyPointsTitle: 'Key Privacy & Data Security Points',
    zeroCustodyTitle: 'Zero Custody of Assets:',
    zeroCustodyText: 'We do not hold your private keys, seed phrases, or digital assets. You have sole, exclusive control over your wallet. We cannot access, recover, or move your funds.',
    privacyByDesignTitle: 'Privacy-by-Design:',
    privacyByDesignText: 'In compliance with the new Law on Personal Data Protection of Bosnia and Herzegovina (Official Gazette of BiH, No. 12/25, aligned with GDPR), this app is built to collect zero personal identifying information (PII).',
    noDataStorageTitle: 'No Data Storage:',
    noDataStorageText: 'We do not store your personal history, location logs, or behavioral data on our servers. Any interaction—including AI queries or image analysis for landmark identification—is processed anonymously.',
    onDeviceProcessingTitle: 'On-Device Processing:',
    onDeviceProcessingText: 'Wherever possible, data processing is handled locally on your own device to ensure your information never leaves your possession.',
    blockchainOffline: 'Blockchain network offline or unreachable.',
    watchCinematic: 'Watch 3D Tour / Cinematic',
    closeVideo: 'Close Video',
    solBalance: 'SOL Balance',
  },
  bs: {
    welcome: 'Dobrodošli u Tuzlu',
    history: 'Historija',
    map: 'Mapa',
    quest: 'Potraga',
    gallery: 'Galerija',
    scanQr: 'Skeniraj QR Kod',
    rewardClaimed: 'Nagrada otključana!',
    discountMessage: 'Dobili ste popust! Pokazite ovo na kasi.',
    notificationTitle: 'Posebna ponuda!',
    notificationBody: 'Cijena Panonskih jezera danas je 5 EUR umjesto 6 EUR!',
    close: 'Zatvori',
    viewOnMap: 'Vidi na mapi',
    foundAt: 'Pronadjeno u',
    liveEvents: 'Dešavanja uživo i vijesti',
    wallet: 'Novčanik',
    loginOAuth: 'Prijava putem OAuth',
    touristInfo: 'Turističke informacije',
    emergencyInfo: 'Hitne informacije',
    bestSupermarket: 'Supermarket',
    workingHours: 'Radno vrijeme',
    monSat: 'Pon - Sub',
    sunday: 'Nedjelja',
    closed: 'Zatvoreno',
    rating: 'Ocjena',
    reviews: 'Recenzije',
    delivery: 'Dostava dostupna',
    noDelivery: 'Nema dostave',
    typicalPrice: 'Tipicna cijena',
    arGuide: 'AR Vodic',
    walletManual: 'Uputstvo za korištenje',
    howToConnect: 'Kako se povezati',
    connectSteps: "1. Kliknite 'Connect Wallet'\n2. Odaberite TON novčanik (Tonkeeper/Telegram)\n3. Potvrdite u aplikaciji",
    safeUsage: 'Sigurno korištenje',
    safeTips: '. Nikad ne dijelite tajne riječi\n. Potvrdite svaku transakciju\n. Koristite zvanične TON aplikacije',
    txHistory: 'Gdje je historija?',
    historyLocation: 'Historija transakcija se čuva u vašoj povezanoj TON aplikaciji.',
    bamToEur: 'Konverzija BAM - EUR',
    enterBam: 'Unesite iznos u BAM',
    calculatedEur: 'Iznos u EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    pannonicaAlt: 'Panonska jezera - Slana jezera u Tuzli',
    pannonicaTitle: 'Dobrodošli na Panoniku',
    pannonicaImage: '/assets/PannonicaBA.webp',
    trademarksDisclaimer: 'Svi logotipi i nazivi brendova su vlasnistvo njihovih vlasnika i koriste se ovdje iskljucivo u informativne svrhe.',
    privacyNoticeTitle: 'Obavjestenje o privatnosti i kameri',
    privacyNoticeBody: 'Ova aplikacija koristi vasu lokaciju iskljucivo za navigaciju do znamenitosti. Kamera se aktivira samo kada ste u neposrednoj blizini (10m) od cilja kako biste skenirali QR kod i pokrenuli AR vodic. Vasa slika i video zapis se ne pohranjuju niti salju na server; sva obrada se vrsi iskljucivo na vasem uredaju. Nastavkom koristenja pristajete na privremeni pristup ovim funkcijama.',
    learnMore: 'Saznajte više',
    busStation: 'Autobuska Stanica Tuzla',
    batteryWarning: 'Štednja baterije aktivna. Smanjite svjetlinu i koristite AR vodic samo u pokretu za duže trajanje.',
    selectNetwork: 'Odaberi mrežu',
    solWallet: 'SOL novčanik',
    switchNetwork: 'Promijeni mrežu',
    connectedToSol: 'Povezan na SOL',
    walletLocked: 'Novčanik Zaključan',
    setWalletPin: 'Postavi PIN novčanika',
    confirmPin: 'Potvrdi PIN',
    enterPin: 'Unesi PIN za otključavanje',
    dentalTourism: 'Stomatološki turizam',
    locationNotAvailable: 'Lokacija nije dostupna.',
    zonesLabel: 'Zone',
    galleryCharmText: 'Nijedna fotografija vam ne može dočarati čar i ljepotu ovog grada, zato dođite i posjetite nas.',
    digitalWalletTitle: 'Digitalni Novčanik',
    solanaConnection: 'Solana Konekcija',
    walletAddress: 'Adresa Novčanika',
    statusNotConnected: 'Nije spojeno',
    viewOnSolanaExplorer: 'Pregledaj na Solana Exploreru',
    explorationTitle: 'Istraživanje',
    qrLocationScannerTitle: 'QR Skeniranje Lokacija',
    startScanner: 'Pokreni',
    qrScannerDesc: 'Pronađite i skenirajte QR kodove na istorijskim znamenitostima širom Tuzle kako biste otključali nagrade u svom vodiču i upisali ih u knjigu.',
    currencyConverterTitle: 'Konvertor Valuta',
    enterBamLabel: 'Unesite Konvertibilne Marke (KM)',
    enterEurLabel: 'Unesite Eure (€)',
    estimatedEurLabel: 'Procijenjeno u EUR',
    estimatedBamLabel: 'Procijenjeno u BAM',
    conversionRateText: 'Kurs: 1 EUR = 1.95583 BAM',
    scanHistoryLedgerTitle: 'Knjiga Skeniranja',
    ledgerEmptyTitle: 'Knjiga je prazna',
    ledgerEmptyDesc: 'Skenirajte lokacije širom grada za popunjavanje istorije.',
    clearScanHistory: 'Očisti Knjigu Skeniranja',
    clearHistoryConfirm: 'Jeste li sigurni?',
    yesDelete: 'Da, obriši',
    cancel: 'Otkaz',
    partnerAgenciesTitle: 'Partnerske Agencije',
    scanLocationToUnlock: 'Skenirajte kod lokacije za otključavanje',
    positionCodeInFrame: 'Pozicionirajte kod unutar okvira',
    success: 'Uspješno',
    error: 'Greška',
    alreadyInLedger: 'je već u vašoj knjizi skeniranja.',
    unlockedLocation: 'Otključana lokacija:',
    unknownQrCode: 'Nepoznat QR kod lokacije.',
    couldNotStartCamera: 'Nije moguće pokrenuti kameru.',
    privacyDisclaimerText: 'Ova aplikacija funkcioniše kao decentralizovani interfejs kojim vi samostalno upravljate. Pružamo alate za interakciju s informacijama i blockchain uslugama, ali vi zadržavate apsolutno vlasništvo i kontrolu nad svojim digitalnim sredstvima i identitetom.',
    privacyKeyPointsTitle: 'Ključne tačke o privatnosti',
    zeroCustodyTitle: 'Potpuna kontrola nad imovinom:',
    zeroCustodyText: 'Ne držimo vaše privatne ključeve, pristupne fraze ili digitalna sredstva. Imate potpunu i ekskluzivnu kontrolu nad svojim novčanikom. Ne možemo pristupiti, vratiti niti premjestiti vaša sredstva.',
    privacyByDesignTitle: 'Privatnost po dizajnu:',
    privacyByDesignText: 'U skladu sa novim Zakonom o zaštiti ličnih podataka Bosne i Hercegovine (Službeni glasnik BiH, br. 12/25, usklađen sa GDPR-om), ova aplikacija je napravljena tako da prikuplja nula ličnih identifikacionih podataka (PII).',
    noDataStorageTitle: 'Bez pohranjivanja podataka:',
    noDataStorageText: 'Ne pohranjujemo vašu ličnu istoriju, dnevnike lokacija ili podatke o ponašanju na našim serverima. Svaka interakcija—uključujući AI upite ili analizu slika za identifikaciju znamenitosti—obrađuje se anonimno.',
    onDeviceProcessingTitle: 'Obrada na samom uređaju:',
    onDeviceProcessingText: 'Gdje god je moguće, obrada podataka se vrši lokalno na vašem uređaju kako bi se osiguralo da vaše informacije nikada ne napuste vaš posjed.',
    blockchainOffline: 'Blockchain mreža nije dostupna.',
    watchCinematic: 'Pogledaj 3D Tour / Video',
    closeVideo: 'Zatvori Video',
    solBalance: 'SOL Saldo',
  },
  de: {
    welcome: 'Willkommen in Tuzla!',
    history: 'Geschichte',
    map: 'Karte',
    quest: 'Quest',
    gallery: 'Galerie',
    scanQr: 'QR-Code scannen',
    rewardClaimed: 'Belohnung freigeschaltet!',
    discountMessage: 'Du hast einen Rabatt bekommen! Zeig das einfach an der Kasse vor.',
    notificationTitle: 'Sonderangebot!',
    notificationBody: 'Die Panonischen Seen kosten heute nur 5 EUR statt 6 EUR!',
    close: 'Schliessen',
    viewOnMap: 'Auf der Karte ansehen',
    foundAt: 'Gefunden bei',
    liveEvents: 'Live-Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login mit OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Notfall-Infos',
    bestSupermarket: 'Bester Supermarkt',
    workingHours: 'Offnungszeiten',
    monSat: 'Mo - Sa',
    sunday: 'Sonntag',
    closed: 'Geschlossen',
    rating: 'Bewertung',
    reviews: 'Bewertungen',
    delivery: 'Lieferung moglich',
    noDelivery: 'Keine Lieferung',
    typicalPrice: 'Normaler Preis',
    arGuide: 'AR-Guide',
    walletManual: 'Bedienungsanleitung',
    howToConnect: 'So verbindest du dich',
    connectSteps: "1. Klick auf 'Connect Wallet'\n2. Wähle eine TON Wallet (Tonkeeper/Telegram) aus\n3. Bestätige alles in deiner App",
    safeUsage: 'Sicherheitstipps',
    safeTips: '. Teil niemals deine Recovery Phrase\n. Bestätige jede Transaktion einzeln\n. Nutze nur offizielle TON Apps',
    txHistory: 'Wo ist der Verlauf?',
    historyLocation: 'Dein Transaktionsverlauf wird direkt in deiner TON Wallet App gespeichert.',
    bamToEur: 'BAM - EUR Umrechner',
    enterBam: 'Betrag in BAM eingeben',
    calculatedEur: 'Gegenwert in EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    pannonicaAlt: 'Panonische Seen - Salzseen in Tuzla',
    pannonicaTitle: 'Willkommen an der Panonica',
    pannonicaImage: '/assets/PannonicaDE.webp',
    trademarksDisclaimer: 'Alle Logos und Markennamen sind Eigentum ihrer jeweiligen Inhaber und werden hier nur zu Informations-/Identifikationszwecken verwendet.',
    privacyNoticeTitle: 'Datenschutz- und Kamerahinweis',
    privacyNoticeBody: 'Diese App verwendet Ihren Standort ausschliesslich zur Navigation zu Sehenswurdigkeiten. Die Kamera wird nur aktiviert, wenn Sie sich im Umkreis von 10m von einem Ziel befinden, um einen QR-Code zu scannen und den AR-Guide zu starten. Ihre Bilder und Video-Feeds werden weder gespeichert noch an Server gesendet; die gesamte Verarbeitung erfolgt ausschliesslich auf Ihrem Gerat. Mit der weiteren Nutzung stimmen Sie dem vorubergehenden Zugriff auf diese Funktionen zu.',
    learnMore: 'Mehr erfahren',
    busStation: 'Busbahnhof',
    batteryWarning: 'Extremer Energiesparmodus aktiv. Helligkeit senken und AR nur bei Bewegung nutzen.',
    selectNetwork: 'Netzwerk wählen',
    solWallet: 'Solana Wallet',
    switchNetwork: 'Netzwerk wechseln',
    connectedToSol: 'Mit Solana verbunden',
    walletLocked: 'Wallet Gesperrt',
    setWalletPin: 'Wallet-PIN festlegen',
    confirmPin: 'PIN bestätigen',
    enterPin: 'PIN zum Entsperren eingeben',
    dentalTourism: 'Zahntourismus',
    locationNotAvailable: 'Standort nicht verfügbar.',
    zonesLabel: 'Zonen',
    galleryCharmText: 'Kein Foto kann Ihnen den Charme und die Schönheit dieser Stadt zeigen, also kommen Sie und besuchen Sie uns.',
    digitalWalletTitle: 'Digitale Geldbörse',
    solanaConnection: 'Solana-Verbindung',
    walletAddress: 'Wallet-Adresse',
    statusNotConnected: 'Nicht verbunden',
    viewOnSolanaExplorer: 'Auf Solana Explorer anzeigen',
    explorationTitle: 'Erkundung',
    qrLocationScannerTitle: 'QR-Standort-Scanner',
    startScanner: 'QR Scannen',
    qrScannerDesc: 'Finden und scannen Sie QR-Codes an historischen Orten in Tuzla, um Belohnungen freizuschalten und im Verlauf einzutragen.',
    currencyConverterTitle: 'Währungsrechner',
    enterBamLabel: 'Konvertible Mark (KM) eingeben',
    enterEurLabel: 'Euro (€) eingeben',
    estimatedEurLabel: 'Geschätzte EUR',
    estimatedBamLabel: 'Geschätzte BAM',
    conversionRateText: 'Kurs: 1 EUR = 1.95583 BAM',
    scanHistoryLedgerTitle: 'Scan-Verlauf',
    ledgerEmptyTitle: 'Verlauf ist leer',
    ledgerEmptyDesc: 'Scannen Sie QR-Codes im Stadtgebiet, um Ihren Verlauf aufzubauen.',
    clearScanHistory: 'Scan-Verlauf löschen',
    clearHistoryConfirm: 'Sind Sie sicher?',
    yesDelete: 'Ja, löschen',
    cancel: 'Abbrechen',
    partnerAgenciesTitle: 'Partneragenturen',
    scanLocationToUnlock: 'QR-Code des Standorts zum Freischalten scannen',
    positionCodeInFrame: 'Positionieren Sie den Code im Rahmen',
    success: 'Erfolg',
    error: 'Fehler',
    alreadyInLedger: 'ist bereits in Ihrem Verlauf.',
    unlockedLocation: 'Freigeschalteter Ort:',
    unknownQrCode: 'Unbekannter Standort-QR-Code.',
    couldNotStartCamera: 'Kamera konnte nicht gestartet werden.',
    privacyDisclaimerText: 'Diese Anwendung funktioniert als nicht- verwahrte, selbst-souveräne Schnittstelle. Wir stellen die Werkzeuge zur Verfügung, mit denen Sie mit Informationen und Blockchain-Diensten interagieren können, aber Sie behalten die absolute Eigentümerschaft und Kontrolle über Ihre digitalen Vermögenswerte und Ihre Identität.',
    privacyKeyPointsTitle: 'Wichtige Datenschutz- und Datensicherheitspunkte',
    zeroCustodyTitle: 'Keine Verwahrung von Vermögenswerten:',
    zeroCustodyText: 'Wir speichern Ihre privaten Schlüssel, Seed-Phrasen oder digitalen Vermögenswerte nicht. Sie haben die alleinige Kontrolle über Ihre Wallet. Wir können nicht auf Ihre Gelder zugreifen.',
    privacyByDesignTitle: 'Privacy-by-Design:',
    privacyByDesignText: 'In Übereinstimmung mit dem neuen Gesetz zum Schutz personenbezogener Daten von Bosnien und Herzegowina (Amtsblatt von BiH, Nr. 12/25, ausgerichtet an DSGVO) sammelt diese App null personenbezogene Daten (PII).',
    noDataStorageTitle: 'Keine Datenspeicherung:',
    noDataStorageText: 'Wir speichern Ihre persönliche Historie, Standortprotokolle oder Verhaltensdaten nicht auf unseren Servern. Jede Interaktion wird anonym verarbeitet.',
    onDeviceProcessingTitle: 'Verarbeitung auf dem Gerät:',
    onDeviceProcessingText: 'Wo immer möglich, erfolgt die Datenverarbeitung lokal auf Ihrem eigenen Gerät, um sicherzustellen, dass Ihre Informationen niemals Ihren Besitz verlassen.',
    blockchainOffline: 'Blockchain-Netzwerk offline oder nicht erreichbar.',
    watchCinematic: '3D-Tour / Video ansehen',
    closeVideo: 'Video schließen',
    solBalance: 'SOL-Guthaben',
  },
  tr: {
    welcome: 'Tuzla\'ya Hoşgeldiniz',
    history: 'Tarih',
    map: 'Harita',
    quest: 'Görev',
    gallery: 'Galeri',
    scanQr: 'QR Kodunu Tara',
    rewardClaimed: 'Ödül Açıldı!',
    discountMessage: 'Bir indirim kazandınız! Bunu kasada gösterin.',
    notificationTitle: 'Özel Teklif!',
    notificationBody: 'Pannonian Gölleri fiyatı bugün 6 EUR yerine 5 EUR!',
    close: 'Kapat',
    viewOnMap: 'Haritada Gör',
    foundAt: 'Bulundu',
    liveEvents: 'Canlı Etkinlikler ve Haberler',
    wallet: 'Cüzdan',
    loginOAuth: 'OAuth ile Giriş Yap',
    touristInfo: 'Turist Bilgisi',
    emergencyInfo: 'Acil Durum Bilgisi',
    bestSupermarket: 'Süpermarket',
    workingHours: 'Çalışma Saatleri',
    monSat: 'Pzt - Cmt',
    sunday: 'Pazar',
    closed: 'Kapalı',
    rating: 'Değerlendirme',
    reviews: 'Yorumlar',
    delivery: 'Teslimat Var',
    noDelivery: 'Teslimat Yok',
    typicalPrice: 'Tipik Fiyat',
    arGuide: 'AR Rehberi',
    walletManual: 'Kullanım Kılavuzu',
    howToConnect: 'Nasıl Bağlanılır',
    connectSteps: "1. 'Connect Wallet'a tıklayın\n2. TON cüzdanını (Tonkeeper/Telegram) seçin\n3. Uygulamada onaylayın",
    safeUsage: 'Güvenli Kullanım',
    safeTips: '. Şifrenizi asla paylaşmayın\n. Her işlemi onaylayın\n. Yalnızca resmi TON uygulamalarını kullanın',
    txHistory: 'Geçmiş nerede?',
    historyLocation: 'İşlem geçmişi bağlı TON cüzdanınıza kaydedilir.',
    bamToEur: 'BAM - EUR Çevrimi',
    enterBam: 'BAM miktarını girin',
    calculatedEur: 'EUR karşılığı',
    conversionRate: 'Kur: 1 BAM = 0.51 EUR (1:1.95583)',
    pannonicaAlt: 'Pannonica Gölleri - Tuzla\'daki Tuz Gölleri',
    pannonicaTitle: 'Pannonica\'ya Hoşgeldiniz',
    pannonicaImage: '/assets/Pannonica.webp',
    trademarksDisclaimer: 'Tüm logolar ve marka isimleri ilgili sahiplerinin mülkiyetindedir ve burada yalnızca bilgi/tanımlama amacıyla kullanılmıştır.',
    privacyNoticeTitle: 'Gizlilik ve Kamera Bildirimi',
    privacyNoticeBody: 'Bu uygulama konumunuzu yalnızca önemli noktalara navigasyon için kullanır. Kamera yalnızca bir hedefe 10m yaklaştığınızda QR kodunu taramak ve AR rehberini başlatmak için etkinleştirilir. Resimleriniz ve video akışınız kaydedilmez veya herhangi bir sunucuya gönderilmez; tüm işlemler yalnızca cihazınızda gerçekleşir. Devam ederek, bu işlevlere geçici erişime izin vermiş olursunuz.',
    learnMore: 'Daha Fazla Bilgi',
    busStation: 'Otobüs Durağı',
    batteryWarning: 'Ekstra Pil Tasarrufu Aktif. Güç tasarrufu için parlaklığı düşürün ve ARyı sadece hareket halindeyken kullanın.',
    selectNetwork: 'Ağ Seçin',
    solWallet: 'Solana Cüzdanı',
    switchNetwork: 'Ağı Değiştir',
    connectedToSol: 'Solana\'ya Bağlı',
    walletLocked: 'Cüzdan Kilitli',
    setWalletPin: 'Cüzdan PIN\'ini Ayarla',
    confirmPin: 'PIN\'i Onayla',
    enterPin: 'Kilidi Açmak İçin PIN Girin',
    dentalTourism: 'Diş Turizmi',
    locationNotAvailable: 'Konum mevcut değil.',
    zonesLabel: 'Bölgeler',
    galleryCharmText: 'Hiçbir fotoğraf size bu şehrin cazibesini ve güzelliğini gösteremez, bu yüzden gelin ve bizi ziyaret edin.',
    digitalWalletTitle: 'Dijital Cüzdan',
    solanaConnection: 'Solana Bağlantısı',
    walletAddress: 'Cüzdan Adresi',
    statusNotConnected: 'Bağlı değil',
    viewOnSolanaExplorer: 'Solana Explorer\'da Görüntüle',
    explorationTitle: 'Keşif',
    qrLocationScannerTitle: 'QR Konum Tarayıcı',
    startScanner: 'QR Tara',
    qrScannerDesc: 'Tuzla etrafındaki tarihi mekanlardaki QR kodlarını tarayarak rehber ödüllerini açın ve tarama defterinize kaydedin.',
    currencyConverterTitle: 'Para Birimi Dönüştürücü',
    enterBamLabel: 'BAM (KM) Girin',
    enterEurLabel: 'EUR (€) Girin',
    estimatedEurLabel: 'Tahmini EUR',
    estimatedBamLabel: 'Tahmini BAM',
    conversionRateText: 'Kur: 1 EUR = 1.95583 BAM',
    scanHistoryLedgerTitle: 'Tarama Geçmişi Defteri',
    ledgerEmptyTitle: 'Defter boş',
    ledgerEmptyDesc: 'Geçmişinizi oluşturmak için şehir etrafındaki konum QR kodlarını tarayın.',
    clearScanHistory: 'Tarama Geçmişini Temizle',
    clearHistoryConfirm: 'Emin misiniz?',
    yesDelete: 'Evet, sil',
    cancel: 'İptal',
    partnerAgenciesTitle: 'Ortak Acenteler',
    scanLocationToUnlock: 'Kilidi açmak için konum QR kodunu tarayın',
    positionCodeInFrame: 'Kodu çerçevenin içine yerleştirin',
    success: 'Başarılı',
    error: 'Hata',
    alreadyInLedger: 'zaten tarama defterinizde.',
    unlockedLocation: 'Açılan konum:',
    unknownQrCode: 'Bilinmeyen konum QR kodu.',
    couldNotStartCamera: 'Kamera başlatılamadı.',
    privacyDisclaimerText: 'Bu uygulama emanetsiz, öz-egemen bir arayüz olarak çalışır. Bilgi ve blockchain hizmetleriyle etkileşime girmeniz için araçlar sunuyoruz, ancak dijital varlıklarınız ve kimliğiniz üzerinde mutlak mülkiyet ve kontrole sahipsiniz.',
    privacyKeyPointsTitle: 'Temel Gizlilik ve Veri Güvenliği Noktaları',
    zeroCustodyTitle: 'Varlıkların Sıfır Emaneti:',
    zeroCustodyText: 'Özel anahtarlarınızı, tohum cümleciklerinizi veya dijital varlıklarınızı tutmuyoruz. Cüzdanınız üzerinde tek ve özel kontrole sahipsiniz. Fonlarınıza erişemeyiz, kurtaramayız veya taşıyamayız.',
    privacyByDesignTitle: 'Tasarım Yoluyla Gizlilik:',
    privacyByDesignText: 'Bosna Hersek Kişisel Verilerin Korunma Kanunu (BiH Resmi Gazetesi, No. 12/25, GDPR ile uyumlu) uyarınca, bu uygulama sıfır kişisel tanımlayıcı bilgi (PII) toplayacak şekilde oluşturulmuştur.',
    noDataStorageTitle: 'Veri Depolama Yok:',
    noDataStorageText: 'Kişisel geçmişinizi, konum günlüklerinizi veya davranışsal verilerinizi sunucularımızda saklamıyoruz. Tüm etkileşimler anonim olarak işlenir.',
    onDeviceProcessingTitle: 'Cihaz Üzerinde İşleme:',
    onDeviceProcessingText: 'Mümkün olan her yerde, bilgilerinizin asla elinizden çıkmamasını sağlamak için veri işlemesi yerel olarak kendi cihazınızda gerçekleştirilir.',
    blockchainOffline: 'Blockchain ağı çevrimdışı veya ulaşılamıyor.',
    watchCinematic: '3D Turu / Videoyu İzle',
    closeVideo: 'Videoyu Kapat',
    solBalance: 'SOL Bakiyesi',
  },
};

const RESTAURANTS_RAW = [
  {
    name: 'Taco Bell',
    address: 'Univerzitetska 16 (Tuzlanka Mall)',
    type: { en: 'Mexican Fast Food', bs: 'Meksicka brza hrana', de: 'Mexikanisches Fast Food', tr: 'Meksika Fast Food' },
    price: '9-18 KM',
    image: '/assets/Gallery/Food/taco.webp',
  },
  {
    name: 'Pekara Hukic',
    address: 'Gradska 59, Tuzla',
    type: { en: 'Traditional Bakery & Pizza', bs: 'Tradicionalna pekara i pizza', de: 'Traditionelle Backerei & Pizza', tr: 'Geleneksel Fırın ve Pizza' },
    price: '3-17 KM',
    image: '/assets/Gallery/Food/huka.webp',
  },
  {
    name: 'Bagi Palačinkara',
    address: 'Patriotske lige 10, Tuzla',
    type: { en: 'Famous Sweet & Sushi Pancakes', bs: 'Poznate slatke i sushi palacinke', de: 'Legendare suse Pfannkuchen & Pancake-Sushi', tr: 'Ünlü Tatlı ve Suşi Krepleri' },
    price: '3-9 KM',
    image: '/assets/Gallery/Food/bagi.webp',
  },
  {
    name: 'Restaurant Saranda',
    address: 'Maršala Tita 88, Tuzla',
    type: { en: 'Traditional Restaurant', bs: 'Tradicionalni restoran', de: 'Traditionelles Restaurant', tr: 'Geleneksel Restoran' },
    price: '10-25 KM',
    image: '/assets/Gallery/Food/saranda.webp',
  },
  {
    name: 'Pizza Trkačica',
    address: 'Nesiba Malkića 20, Tuzla',
    type: { en: 'Pizza & Delivery', bs: 'Pizza i dostava', de: 'Pizza & Lieferservice', tr: 'Pizza ve Teslimat' },
    price: '6-18 KM',
    image: '/assets/Gallery/Food/trkacica.webp',
  },
  {
    name: 'Mamma Mia Origins',
    address: 'Trg slobode bb, Tuzla',
    type: { en: 'Steak & Wine / Upscale', bs: 'Steak & Wine / Elitno', de: 'Steak & Wein / Gehoben', tr: 'Biftek ve Şarap / Lüks' },
    price: '20-60 KM',
    image: '/assets/Gallery/Food/mia.webp',
  },
  {
    name: 'Papi Gelato',
    address: 'Hadžihasanage Pašića 3, Tuzla',
    type: { en: 'Artisanal Gelato', bs: 'Artisan sladoled', de: 'Hausgemachtes Eis', tr: 'Zanaat Dondurması' },
    price: '3-10 KM',
    image: '/assets/Gallery/Food/papi.webp',
  },
  {
    name: 'Restaurant Sedra',
    address: 'Slatina 5, Tuzla',
    type: { en: 'Traditional Dining', bs: 'Tradicionalna kuhinja', de: 'Traditionelle Küche', tr: 'Geleneksel Mutfak' },
    price: '8-22 KM',
    image: '/assets/Gallery/Food/sedra.webp',
  },
  {
    name: 'Alibaba Restoran',
    address: 'Toplice 1, Tuzla',
    type: { en: 'Traditional Atmosphere', bs: 'Tradicionalni ambijent', de: 'Traditionelles Ambiente', tr: 'Geleneksel Atmosfer' },
    price: '7-20 KM',
    image: '/assets/Gallery/Food/alibaba.webp',
  },
  {
    name: 'Gradska Kafana',
    address: 'ZAVNOBiH-a 13, Tuzla',
    type: { en: 'Classic Café', bs: 'Klasična kafana', de: 'Klassisches Café', tr: 'Klasik Kafe' },
    price: '2-8 KM',
    image: '/assets/Gallery/Food/kafana.webp',
  },
  {
    name: 'Čevabdžinica Limenka',
    address: 'Patriotske lige 24, Tuzla',
    type: { en: 'Iconic Ćevapi Spot', bs: 'Kultna ćevabdžinica', de: 'Kult-Ćevapi-Laden', tr: 'İkonik Köfteci' },
    price: '5-12 KM',
    image: '/assets/Gallery/Food/limenka.webp',
  },
  {
    name: 'Mozaik',
    address: 'Turalibegova 2, Tuzla',
    type: { en: 'International Restaurant', bs: 'Internacionalni restoran', de: 'Internationales Restaurant', tr: 'Uluslararası Restoran' },
    price: '10-30 KM',
    image: '/assets/Gallery/Food/mozaik.webp',
  },
  {
    name: 'Fast Food King',
    address: 'TC Sjenjak (15. maja bb), Tuzla',
    type: { en: 'Burgers & Fries', bs: 'Burgeri i pomfrit', de: 'Burger & Pommes', tr: 'Burger ve Patates' },
    price: '5-15 KM',
    image: '/assets/Gallery/Food/king.webp',
  },
  {
    name: 'Sezam Tennis',
    address: 'Šetalište Slana Banja bb, Tuzla',
    type: { en: 'Pizza & Grill', bs: 'Pizza i roštilj', de: 'Pizza & Grill', tr: 'Pizza ve Izgara' },
    price: '7-20 KM',
    image: '/assets/Gallery/Food/foodprime.webp',
  },
  {
    name: 'Pizzeria La Linea',
    address: 'Stupine B2, Tuzla',
    type: { en: 'Pizza & Pasta', bs: 'Pizza i pasta', de: 'Pizza & Pasta', tr: 'Pizza ve Makarna' },
    price: '6-18 KM',
    image: '/assets/Gallery/Food/lineaaa.webp',
  },
  {
    name: 'Ćevabdžinica Brajlović',
    address: 'Fra Stjepana Matijevića Solinjanina 1, Tuzla',
    type: { en: 'Traditional Ćevapi', bs: 'Tradicionalni ćevapi', de: 'Traditionelle Ćevapi', tr: 'Geleneksel Köfte' },
    price: '7-15 KM',
    image: '/assets/Gallery/Food/cevapibrajlovic.webp'
  },
  {
    name: 'Smash Bos Burger',
    address: 'Turalibegova 48 (zgrada Cipelići), Tuzla',
    type: { en: 'Modern Smash Burgers', bs: 'Moderni smash burgeri', de: 'Moderne Smash Burger', tr: 'Modern Smash Burgerler' },
    price: '8-16 KM',
    image: '/assets/Gallery/Food/smashbosbur.webp'
  },
  {
    name: 'Zdravljak Bosna',
    address: 'Muhameda H. Uskufija 8, Tuzla',
    type: { en: 'Traditional Bosnian Food', bs: 'Tradicionalna bosanska hrana', de: 'Traditionelles bosnisches Essen', tr: 'Geleneksel Boşnak Yemeği' },
    price: '10-30 KM',
    image: '/assets/Gallery/Food/bosna.webp'
  },
];

export const TUZLA_DINING_DATA: LocationData[] = [
  {
    name: 'Taco Bell Tuzla',
    rating: 4.3,
    user_ratings_total: 189,
    address: 'Univerzitetska 16, Tuzla',
    latitude: 44.538497,
    longitude: 18.664660,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/taco.webp',
  },
  {
    name: 'Pekara Hukic',
    rating: 4.6,
    user_ratings_total: 410,
    address: 'Gradska 59, Tuzla',
    latitude: 44.539500,
    longitude: 18.674000,
    category: 'Bakery',
    type: 'Dining',
    image: '/assets/Gallery/Food/huka.webp',
  },
  {
    name: 'Libero Caffe',
    rating: 4.5,
    user_ratings_total: 278,
    address: 'Armije Republike Bosne i Hercegovine 17, Tuzla',
    latitude: 44.542283,
    longitude: 18.693450,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/libero.webp',
  },
  {
    name: 'Nota Bene Pizzeria',
    rating: 4.8,
    user_ratings_total: 320,
    address: 'I inžinjerske brigade bb (zgrada Titanik), Tuzla',
    latitude: 44.534160,
    longitude: 18.698330,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/notabene.webp',
  },
  {
    name: 'Mozaik',
    rating: 4.7,
    user_ratings_total: 493,
    address: 'Turalibegova 2, Tuzla',
    latitude: 44.537233,
    longitude: 18.674936,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/mozaik.webp',
  },
  {
    name: 'Pizza Trkačica',
    rating: 4.9,
    user_ratings_total: 211,
    address: 'Nesiba Malkića 20, Tuzla',
    latitude: 44.525767,
    longitude: 18.696539,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/trkacica.webp',
    website: 'http://trkacica.com/'
  },
  {
    name: 'Fast Food King',
    rating: 4.9,
    user_ratings_total: 257,
    address: 'TC Sjenjak (15. maja bb), Tuzla',
    latitude: 44.530500,
    longitude: 18.702500,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/king.webp',
  },
  {
    name: 'Sezam Tennis',
    rating: 4.9,
    user_ratings_total: 59,
    address: 'Šetalište Slana Banja bb, Tuzla',
    latitude: 44.539200,
    longitude: 18.686500,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/foodprime.webp',
  },
  {
    name: 'Pizzeria La Linea',
    rating: 4.9,
    user_ratings_total: 47,
    address: 'Stupine B2, Tuzla',
    latitude: 44.531200,
    longitude: 18.688800,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/lineaaa.webp',
  },
  {
    name: 'Restaurant Saranda',
    rating: 4.4,
    user_ratings_total: 245,
    address: 'Maršala Tita 88, Tuzla',
    latitude: 44.5343,
    longitude: 18.6944,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/saranda.webp',
    website: 'http://www.saranda.ba/'
  },
  {
    name: 'Mama Mia Origins',
    rating: 4.7,
    user_ratings_total: 156,
    address: 'Univerzitetska 16 (RK Tuzlanka), Tuzla',
    latitude: 44.5385,
    longitude: 18.6648,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/mia.webp',
    website: 'https://mamamiaorigins.com/'
  },
  {
    name: 'Papi Gelato',
    rating: 4.8,
    user_ratings_total: 312,
    address: 'Hadžihasanage Pašića 3, Tuzla',
    latitude: 44.5386,
    longitude: 18.6753,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/papi.webp'
  },
  {
    name: 'Restaurant Sedra',
    rating: 4.4,
    user_ratings_total: 189,
    address: 'Slatina 5, Tuzla',
    latitude: 44.5375,
    longitude: 18.6630,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/sedra.webp',
    website: 'https://sedra.ba/'
  },
  {
    name: 'Alibaba Restoran',
    rating: 4.5,
    user_ratings_total: 124,
    address: 'Nesiba Malkića 1, Tuzla',
    latitude: 44.5305,
    longitude: 18.6945,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/alibaba.webp'
  },
  {
    name: 'Gradska Kafana',
    rating: 4.3,
    user_ratings_total: 278,
    address: 'ZAVNOBiH-a 13, Tuzla',
    latitude: 44.5390,
    longitude: 18.6750,
    category: 'Café',
    type: 'Dining',
    image: '/assets/Gallery/Food/kafana.webp'
  },
  {
    name: 'Čevabdžinica Limenka',
    rating: 4.7,
    user_ratings_total: 540,
    address: 'Patriotske lige 24, Tuzla',
    latitude: 44.5394,
    longitude: 18.6825,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/limenka.webp',
    website: 'http://www.limenka.ba/'
  },
  {
    name: 'Bagi Palačinkara',
    rating: 4.9,
    user_ratings_total: 856,
    address: 'Patriotske lige 10, Tuzla',
    latitude: 44.5392,
    longitude: 18.6755,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/bagi.webp'
  },
  {
    name: 'Choco Loco',
    rating: 4.8,
    user_ratings_total: 420,
    address: 'Hadžibakirbega Tuzlića bb, Tuzla',
    latitude: 44.5384,
    longitude: 18.6742,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/chocoloco.webp'
  },
  {
    name: 'Ćevabdžinica Brajlović',
    rating: 4.7,
    user_ratings_total: 124,
    address: 'Fra Stjepana Matijevića Solinjanina 1, Tuzla',
    latitude: 44.5402,
    longitude: 18.6725,
    category: 'Traditional',
    type: 'Dining',
    image: '/assets/Gallery/Food/cevapibrajlovic.webp'
  },
  {
    name: 'Smash Bos Burger',
    rating: 4.8,
    user_ratings_total: 98,
    address: 'Turalibegova 48 (zgrada Cipelići), Tuzla',
    latitude: 44.5375,
    longitude: 18.6795,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/smashbosbur.webp'
  },
  {
    name: 'Zdravljak Bosna',
    rating: 4.6,
    user_ratings_total: 156,
    address: 'Muhameda H. Uskufija 8, Tuzla',
    latitude: 44.5385,
    longitude: 18.6770,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/bosna.webp'
  },
];

export const ALL_TUZLA_VENUES = TUZLA_DINING_DATA;

export const LOCATIONS = LOCATIONS_RAW;
export const BINGO_STORE = BINGO_STORE_RAW;
export const TRANSLATIONS: Record<Language, TranslationSet> = TRANSLATIONS_RAW;
export const RESTAURANTS = RESTAURANTS_RAW;

export const TUZLA_WIFI_DATA: WifiSpot[] = [
  {
    id: "wifi-trg-slobode",
    name: {
      en: "Free WiFi - Freedom Square",
      bs: "Besplatan WiFi - Trg Slobode",
      de: "Kostenloses WLAN - Freiheitsplatz",
      tr: "Ücretsiz WiFi - Özgürlük Meydanı"
    },
    description: {
      en: "High-speed public WiFi available throughout Freedom Square. Provided by the City of Tuzla.",
      bs: "Brzi javni WiFi dostupan na cijelom području Trga Slobode. Obezbjeđuje Grad Tuzla.",
      de: "Schnelles öffentliches WLAN auf dem gesamten Freiheitsplatz. Bereitgestellt von der Stadt Tuzla.",
      tr: "Özgürlük Meydanı genelinde yüksek hızlı ücretsiz kamu WiFi. Tuzla Belediyesi tarafından sağlanmaktadır."
    },
    latitude: 44.53956,
    longitude: 18.67570,
    ssid: "Tuzla_Free_WiFi"
  },
  {
    id: "wifi-panonika",
    name: {
      en: "Free WiFi - Pannonian Lakes",
      bs: "Besplatan WiFi - Panonska Jezera",
      de: "Kostenloses WLAN - Pannonische Seen",
      tr: "Ücretsiz WiFi - Pannonian Gölleri"
    },
    description: {
      en: "Free WiFi coverage near the main entrance and first lake area. Active during summer season.",
      bs: "Besplatan WiFi signal u blizini glavnog ulaza i prvog jezera. Aktivno tokom ljetne sezone.",
      de: "Kostenloser WLAN-Empfang in der Nähe des Haupteingangs und des ersten Sees. Aktiv während der Sommersaison.",
      tr: "Ana giriş ve ilk göl bölgesi yakınında ücretsiz WiFi kapsama alanı. Yaz sezonu boyunca aktiftir."
    },
    latitude: 44.53880,
    longitude: 18.68005,
    ssid: "Panonika_Guest"
  },
  {
    id: "wifi-slana-banja",
    name: {
      en: "Free WiFi - Slana Banja Park",
      bs: "Besplatan WiFi - Slana Banja",
      de: "Kostenloses WLAN - Slana Banja Park",
      tr: "Ücretsiz WiFi - Slana Banja Parkı"
    },
    description: {
      en: "Free public WiFi coverage around the central memorial area of Slana Banja Park.",
      bs: "Besplatan javni WiFi signal oko centralnog spomen-obilježja u parku Slana Banja.",
      de: "Kostenloses öffentliches WLAN rund um den zentralen Gedenkbereich des Slana Banja Parks.",
      tr: "Slana Banja Parkı'nın merkezi anıt alanı çevresinde ücretsiz kamu WiFi."
    },
    latitude: 44.53820,
    longitude: 18.68540,
    ssid: "Slana_Banja_Free"
  },
  {
    id: "wifi-soni-trg",
    name: {
      en: "Free WiFi - Salt Square",
      bs: "Besplatan WiFi - Soni Trg",
      de: "Kostenloses WLAN - Salzplatz",
      tr: "Ücretsiz WiFi - Tuz Meydanı"
    },
    description: {
      en: "Free municipal WiFi network surrounding the historic Salt Square.",
      bs: "Besplatna gradska WiFi mreža na prostoru istorijskog Sonog Trga.",
      de: "Kostenloses städtisches WLAN-Netzwerk rund um den historischen Salzplatz.",
      tr: "Tarihi Tuz Meydanı'nı çevreleyen ücretsiz belediye WiFi ağı."
    },
    latitude: 44.53877,
    longitude: 18.67305,
    ssid: "Grad_Tuzla_WiFi"
  },
  {
    id: "wifi-bcc",
    name: {
      en: "Free WiFi - Bingo City Center",
      bs: "Besplatan WiFi - Bingo City Center",
      de: "Kostenloses WLAN - Bingo City Center",
      tr: "Ücretsiz WiFi - Bingo City Center"
    },
    description: {
      en: "High-speed mall WiFi available for all visitors. Connect and browse instantly.",
      bs: "Brzi WiFi tržnog centra dostupan za sve posjetioce. Povežite se i surfajte odmah.",
      de: "Schnelles WLAN im Einkaufszentrum für alle Besucher. Sofort verbinden und surfen.",
      tr: "Tüm ziyaretçiler için yüksek hızlı alışveriş merkezi WiFi. Anında bağlanın ve göz atın."
    },
    latitude: 44.53185,
    longitude: 18.65215,
    ssid: "BCC_FREE_WIFI"
  }
];

