import { Language, TranslationSet, Location, LocationData, ParkingLot, WifiSpot } from "./types";

export const TUZLA_CENTER: [number, number] = [44.5388, 18.6750];

const LOCATIONS_RAW: Location[] = [
  {
    id: '1',
    name: {
      en: 'Pannonian Lakes',
      bs: 'Panonska jezera',
      de: 'Panonische Seen',
      tr: 'Pannonian Gölleri',
    },
    description: {
      en: 'The only salt lakes in Europe located in the city center. A unique complex of three lakes with medicinal properties.',
      bs: 'Jedina slana jezera u Evropi u centru grada. Jedinstven kompleks tri jezera sa ljekovitim svojstvima.',
      de: 'Die einzigen Salzseen in Europa direkt im Stadtzentrum. Einzigartiger Komplex aus drei Seen mit heilender Wirkung.',
      tr: 'Şehir merkezinde bulunan Avrupa\'nın tek tuz gölleri. Tıbbi özelliklere sahip üç gölden oluşan eşsiz bir kompleks.',
    },
    image: '/assets/Gallery/QuestQRLocations/Panonsko jezero.png',
    coordinates: [44.5385, 18.6767],
    category: 'nature',
    qrCode: 'Pannonian Lakes',
    discount: '10%',
  },
  {
    id: '2',
    name: {
      en: 'Old Town (Carsija)',
      bs: 'Stari grad (Carsija)',
      de: 'Altstadt (Carsija)',
      tr: 'Eski Şehir (Çarşı)',
    },
    description: {
      en: 'The historic heart of Tuzla with Ottoman architecture, cafes, and Freedom Square.',
      bs: 'Historijsko srce Tuzle sa otomanskom arhitekturom, kaficima i Trgom slobode.',
      de: 'Das historische Herz von Tuzla mit osmanischer Architektur, Cafes und dem Freiheitsplatz.',
      tr: 'Osmanlı mimarisi, kafeler ve Özgürlük Meydanı ile Tuzla\'nın tarihi kalbi.',
    },
    image: '/assets/Gallery/QuestQRLocations/TuzlaMenuLogo.png',
    coordinates: [44.5391, 18.6750],
    category: 'culture',
    qrCode: 'Old Town',
    discount: '10%',
  },
  {
    id: '3',
    name: {
      en: 'Salt Square',
      bs: 'Trg soli',
      de: 'Salzplatz',
      tr: 'Tuz Meydanı',
    },
    description: {
      en: 'A square celebrating Tuzla s 2,500-year salt history with a replica salt well.',
      bs: 'Trg posvecen tuzlanskoj 2.500 godina dugoj historiji proizvodnje soli, sa replikom bunara za so.',
      de: 'Ein Platz, der Tuzlas 2.500-jahrige Geschichte der Salzgewinnung feiert, inklusive einer Replik eines Salzbrunnens.',
      tr: 'Tuzla\'nın 2.500 yıllık tuz tarihini bir tuz kuyusu kopyasıyla kutlayan bir meydan.',
    },
    image: '/assets/Gallery/QuestQRLocations/TuzlaMenuLogo.png',
    coordinates: [44.5388, 18.6732],
    category: 'culture',
    qrCode: 'Salt Square',
    discount: 5,
  },
  {
    id: '4',
    name: {
      en: 'Ilincica Hill',
      bs: 'Brdo Ilincica',
      de: 'Ilincica Hugel',
      tr: 'İlinçica Tepesi',
    },
    description: {
      en: 'A popular recreational area offering a panoramic view of the city, perfect for hiking and picnics.',
      bs: 'Popularno izletiste sa panoramskim pogledom na grad, savrseno za planinarenje i piknike.',
      de: 'Ein beliebtes Naherholungsgebiet mit Panoramablick uber die Stadt, perfekt zum Wandern und Picknicken.',
      tr: 'Şehrin panoramik manzarasını sunan, yürüyüş ve piknik için mükemmel popüler bir dinlenme alanı.',
    },
    image: '/assets/Gallery/QuestQRLocations/ilincicaba.webp',
    coordinates: [44.5300, 18.6800],
    category: 'nature',
    qrCode: 'Ilincica Hill',
    discount: 'Health 100%',
  },
  {
    id: '5',
    name: {
      en: 'Tuzlanka Mall',
      bs: 'RK Tuzlanka',
      de: 'Tuzlanka Einkaufszentrum',
      tr: 'Tuzlanka Alışveriş Merkezi',
    },
    description: {
      en: 'One of the city s main shopping destinations with a variety of international and local brands.',
      bs: 'Jedna od glavnih shopping destinacija u gradu sa raznim medjunarodnim i lokalnim brendovima.',
      de: 'Eines der wichtigsten Einkaufsziele der Stadt mit vielen internationalen und lokalen Marken.',
      tr: 'Çeşitli uluslararası ve yerel markaların bulunduğu şehrin ana alışveriş noktalarından biri.',
    },
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=400',
    coordinates: [44.5381, 18.6650],
    category: 'shopping',
    qrCode: 'Tuzlanka Mall',
    discount: 10,
  },
  {
    id: 'mesa_selimovic',
    name: {
      en: 'Mesa Selimovic Statue',
      bs: 'Kip Meše Selimovića',
      de: 'Mesa-Selimovic-Statue',
      tr: 'Meşa Selimoviç Heykeli',
    },
    description: {
      en: 'Statue of the famous writer Mesa Selimovic.',
      bs: 'Kip poznatog pisca Meše Selimovica.',
      de: 'Statue des beruehmten Schriftstellers Mesa Selimovic.',
      tr: 'Ünlü yazar Meşa Selimoviç\'in heykeli.',
    },
    image: '/assets/Gallery/mesaselimovic.webp',
    coordinates: [44.5370993, 18.6781216],
    category: 'culture',
    qrCode: 'Mesa Selimovic',
    discount: 'Video Reward',
  },
  {
    id: 'tvrtko_park',
    name: {
      en: 'King Tvrtko Park',
      bs: 'Park Kralja Tvrtka I',
      de: 'Koenig-Tvrtko-Park',
      tr: 'Kral Tvrtko Parkı',
    },
    description: {
      en: 'Central City Park featuring the monument of King Tvrtko I, the first Bosnian king.',
      bs: 'Centralni gradski park sa spomenikom Kralju Tvrtku I, prvom bosanskom kralju.',
      de: 'Zentraler Stadtpark mit dem Denkmal von Koenig Tvrtko I., dem ersten bosnischen Koenig.',
      tr: 'Bosna\'nın ilk kralı olan I. Kral Tvrtko\'nun anıtının bulunduğu merkezi şehir parkı.',
    },
    image: '/assets/Gallery/QuestQRLocations/Tvrko pannellum/KraljTvrko11.webp',
    coordinates: [44.5380826, 18.6783327],
    category: 'culture',
    qrCode: 'King Tvrtko',
    discount: 'Virtual Discovery',
  },
  {
    id: 'bingo_city_centar',
    name: {
      en: 'Bingo City Center',
      bs: 'Bingo City Centar',
      de: 'Bingo City Einkaufszentrum',
      tr: 'Bingo City Alışveriş Merkezi',
    },
    description: {
      en: 'The largest shopping mall in the region with numerous stores, cinemas, and entertainment options.',
      bs: 'Najveći tržni centar u regiji sa brojnim trgovinama, kinom i zabavnim sadržajima.',
      de: 'Das größte Einkaufszentrum der Region mit zahlreichen Geschäften, Kinos und Unterhaltungsangeboten.',
      tr: 'Bölgenin çok sayıda mağaza, sinema ve eğlence seçeneği sunan en büyük alışveriş merkezi.',
    },
    image: '/assets/Gallery/QuestQRLocations/Bingo City Centar.png',
    coordinates: [44.532177, 18.651743],
    category: 'culture',
    qrCode: 'Bingo City Centar',
    discount: 'Special Rewards',
    website: 'https://tuzla.bingocitycenter.ba/',
  },
  {
    id: 'atelje_ismet',
    name: {
      en: 'Atelje Ismet Mujezinovic',
      bs: 'Atelje Ismet Mujezinović',
      de: 'Ismet Mujezinovic Atelier',
      tr: 'Ismet Mujezinovic Atölyesi',
    },
    description: {
      en: 'The former studio and gallery of the famous Bosnian painter Ismet Mujezinović.',
      bs: 'Bivši atelje i galerija poznatog bosanskog slikara Ismeta Mujezinovića.',
      de: 'Das ehemalige Atelier und die Galerie des berühmten bosnischen Malers Ismet Mujezinović.',
      tr: 'Ünlü Bosnalı ressam Ismet Mujezinović\'in eski atölyesi ve galerisi.',
    },
    image: '/assets/Gallery/QuestQRLocations/Atelje Ismet Mujezinovic.png',
    coordinates: [44.5385, 18.6850],
    category: 'culture',
    qrCode: 'Atelje Ismet Mujezinovic',
    discount: 'Art Reward',
  },
  {
    id: 'slana_banja',
    name: {
      en: 'Slana Banja Park',
      bs: 'Slana Banja',
      de: 'Slana Banja Park',
      tr: 'Slana Banja Parkı',
    },
    description: {
      en: 'A memorial park and recreational area with beautiful walk paths and historical monuments.',
      bs: 'Memorijalni park i rekreaciona zona sa prelijepim stazama i historijskim spomenicima.',
      de: 'Ein Gedenkpark und Erholungsgebiet mit schönen Wanderwegen und historischen Denkmälern.',
      tr: 'Güzel yürüyüş yolları ve tarihi anıtların bulunduğu bir anıt parkı ve dinlenme alanı.',
    },
    image: '/assets/Gallery/QuestQRLocations/QR Banja.png',
    coordinates: [44.5385, 18.6820],
    category: 'nature',
    qrCode: 'Banja',
    discount: 'Health Reward',
  }
];

const BINGO_STORE_RAW = {
  name: 'Bingo Supermarket',
  address: 'Mitra Trifunovica Uce 2, Tuzla',
  rating: '100%',
  hours: {
    en: { monSat: '08:00 - 20:30', sun: 'Closed' },
    bs: { monSat: '08:00 - 20:30', sun: 'Zatvoreno' },
    de: { monSat: '08:00 - 20:30', sun: 'Geschlossen' },
    tr: { monSat: '08:00 - 20:30', sun: 'Kapalı' },
  },
  items: [
    { name: 'Fresh Fruit', price: 'Varies', image: '/assets/Gallery/Fruit.webp' },
    { name: 'Quality Meat', price: 'Varies', image: '/assets/Gallery/Meat.webp' },
    { name: 'Charcuterie', price: 'Varies', image: '/assets/Gallery/Charcuterie.webp' },
    { name: 'Vegetables & Herbs', price: 'Varies', image: '/assets/Gallery/Vegetables___Herbs.webp' },
  ],
};



const TRANSLATIONS_RAW: Record<Language, TranslationSet> = {
  en: {
    welcome: 'Welcome to Tuzla',
    history: 'History',
    map: 'Map',
    quest: 'Quest',
    gallery: 'Gallery',
    scanQr: 'Scan QR Code',
    rewardClaimed: 'Reward Unlocked!',
    discountMessage: 'You received a discount! Show this at the counter.',
    notificationTitle: 'Special Offer!',
    notificationBody: 'Pannonian Lakes price is now 5 EUR instead of 6 EUR today!',
    close: 'Close',
    viewOnMap: 'View on Map',
    foundAt: 'Found at',
    liveEvents: 'Live Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login with OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Emergency Info',
    bestSupermarket: 'Supermarket',
    workingHours: 'Working Hours',
    monSat: 'Mon - Sat',
    sunday: 'Sunday',
    closed: 'Closed',
    rating: 'Rating',
    reviews: 'Reviews',
    delivery: 'Delivery Available',
    noDelivery: 'No Delivery',
    typicalPrice: 'Typical Price',
    arGuide: 'AR Guide',
    walletManual: 'User Manual',
    howToConnect: 'How to Connect',
    connectSteps: "1. Click 'Connect Wallet'\n2. Choose a TON wallet (Tonkeeper/Telegram)\n3. Confirm in your app",
    safeUsage: 'Safe Usage',
    safeTips: '. Never share your seed phrase\n. Confirm every transaction\n. Use official TON apps only',
    txHistory: 'Where is history?',
    historyLocation: 'Transaction history is saved within your connected TON wallet app.',
    bamToEur: 'BAM - EUR Conversion',
    enterBam: 'Enter amount in BAM',
    calculatedEur: 'Equivalent in EUR',
    conversionRate: 'Rate: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Pannonica Lakes - Salt Lakes in Tuzla',
    pannonicaTitle: 'Welcome to Pannonica',
    pannonicaImage: '/assets/Pannonica.webp',
    parkingTitle: 'Parking',
    parkingActive: 'Active Parking',
    parkingAutoDetect: 'Auto Detect My Zone',
    parkingLicensePlate: 'License Plate',
    parkingHourly: 'Hourly',
    parkingDaily: 'Daily',
    parkingPaySms: 'Pay via SMS',
    parkingDetectNoZone: 'No parking zone detected.',
    parkingPromptPlate: 'Confirm zone and enter plate.',
    parkingPaymentInactive: 'Parking payment not active at this time.',
    parkingConfirm: 'Confirm',
    parkingCancel: 'Cancel',
    parkingDetected: 'Detected',
    trademarksDisclaimer: 'All logos and brand names are properties of their respective owners and are used here for informational/identification purposes only.',
    privacyNoticeTitle: 'Privacy & Camera Notice',
    privacyNoticeBody: 'This app uses your location solely for navigation to points of interest. The camera is activated only when you are within 10m of a destination to scan a QR code and trigger the AR guide. Your images and video feed are not stored or sent to any server; all processing occurs strictly on your device. By continuing, you consent to temporary access to these functions.',
    learnMore: 'Learn More',
    busStation: 'Bus Station',
    batteryWarning: 'Extreme Battery Saver Active. Lower brightness and use AR only when moving to preserve power.',
    selectNetwork: 'Select Network',
    tonWallet: 'TON Wallet',
    switchNetwork: 'Switch Network',
    connectedToTon: 'Connected to TON',
    walletLocked: 'Wallet Locked',
    setWalletPin: 'Set Wallet PIN',
    confirmPin: 'Confirm PIN',
    enterPin: 'Enter PIN to Unlock',
    dentalTourism: 'Dental Tourism',
    parkingSearch: 'Search parking lots...',
    locationNotAvailable: 'Location not available.',
    zonesLabel: 'Zones',
    galleryCharmText: 'No photo can show you charm and beauty of this city, so come and visit us.',
  },
  bs: {
    welcome: 'Dobrodošli u Tuzlu',
    history: 'Historija',
    map: 'Mapa',
    quest: 'Potraga',
    gallery: 'Galerija',
    scanQr: 'Skeniraj QR Kod',
    rewardClaimed: 'Nagrada otključana!',
    discountMessage: 'Dobili ste popust! Pokazite ovo na kasi.',
    notificationTitle: 'Posebna ponuda!',
    notificationBody: 'Cijena Panonskih jezera danas je 5 EUR umjesto 6 EUR!',
    close: 'Zatvori',
    viewOnMap: 'Vidi na mapi',
    foundAt: 'Pronadjeno u',
    liveEvents: 'Dešavanja uživo i vijesti',
    wallet: 'Novčanik',
    loginOAuth: 'Prijava putem OAuth',
    touristInfo: 'Turističke informacije',
    emergencyInfo: 'Hitne informacije',
    bestSupermarket: 'Supermarket',
    workingHours: 'Radno vrijeme',
    monSat: 'Pon - Sub',
    sunday: 'Nedjelja',
    closed: 'Zatvoreno',
    rating: 'Ocjena',
    reviews: 'Recenzije',
    delivery: 'Dostava dostupna',
    noDelivery: 'Nema dostave',
    typicalPrice: 'Tipicna cijena',
    arGuide: 'AR Vodic',
    walletManual: 'Uputstvo za korištenje',
    howToConnect: 'Kako se povezati',
    connectSteps: "1. Kliknite 'Connect Wallet'\n2. Odaberite TON novčanik (Tonkeeper/Telegram)\n3. Potvrdite u aplikaciji",
    safeUsage: 'Sigurno korištenje',
    safeTips: '. Nikad ne dijelite tajne riječi\n. Potvrdite svaku transakciju\n. Koristite zvanične TON aplikacije',
    txHistory: 'Gdje je historija?',
    historyLocation: 'Historija transakcija se čuva u vašoj povezanoj TON aplikaciji.',
    bamToEur: 'Konverzija BAM - EUR',
    enterBam: 'Unesite iznos u BAM',
    calculatedEur: 'Iznos u EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Panonska jezera - Slana jezera u Tuzli',
    pannonicaTitle: 'Dobrodošli na Panoniku',
    pannonicaImage: '/assets/PannonicaBA.webp',
    parkingTitle: 'Parking',
    parkingActive: 'Aktivni parking',
    parkingAutoDetect: 'Automatski detektuj zonu',
    parkingLicensePlate: 'Registarska oznaka',
    parkingHourly: 'Satni',
    parkingDaily: 'Dnevni',
    parkingPaySms: 'Plati putem SMS-a',
    parkingDetectNoZone: 'Parking zona nije detektovana.',
    parkingPromptPlate: 'Potvrdite zonu i unesite registraciju.',
    parkingPaymentInactive: 'Placanje parkinga trenutno nije aktivno.',
    parkingConfirm: 'Potvrdi',
    parkingCancel: 'Ponisti',
    parkingDetected: 'Detektovano',
    trademarksDisclaimer: 'Svi logotipi i nazivi brendova su vlasnistvo njihovih vlasnika i koriste se ovdje iskljucivo u informativne svrhe.',
    privacyNoticeTitle: 'Obavjestenje o privatnosti i kameri',
    privacyNoticeBody: 'Ova aplikacija koristi vasu lokaciju iskljucivo za navigaciju do znamenitosti. Kamera se aktivira samo kada ste u neposrednoj blizini (10m) od cilja kako biste skenirali QR kod i pokrenuli AR vodic. Vasa slika i video zapis se ne pohranjuju niti salju na server; sva obrada se vrsi iskljucivo na vasem uredaju. Nastavkom koristenja pristajete na privremeni pristup ovim funkcijama.',
    learnMore: 'Saznajte više',
    busStation: 'Autobuska Stanica Tuzla',
    batteryWarning: 'Štednja baterije aktivna. Smanjite svjetlinu i koristite AR vodic samo u pokretu za duže trajanje.',
    selectNetwork: 'Odaberi mrežu',
    tonWallet: 'SOL novčanik',
    switchNetwork: 'Promijeni mrežu',
    connectedToTon: 'Povezan na SOL',
    walletLocked: 'Novčanik Zaključan',
    setWalletPin: 'Postavi PIN novčanika',
    confirmPin: 'Potvrdi PIN',
    enterPin: 'Unesi PIN za otključavanje',
    dentalTourism: 'Stomatološki turizam',
    parkingSearch: 'Pretraži parkinge...',
    locationNotAvailable: 'Lokacija nije dostupna.',
    zonesLabel: 'Zone',
    galleryCharmText: ""
  },
  de: {
    welcome: 'Willkommen in Tuzla!',
    history: 'Geschichte',
    map: 'Karte',
    quest: 'Quest',
    gallery: 'Galerie',
    scanQr: 'QR-Code scannen',
    rewardClaimed: 'Belohnung freigeschaltet!',
    discountMessage: 'Du hast einen Rabatt bekommen! Zeig das einfach an der Kasse vor.',
    notificationTitle: 'Sonderangebot!',
    notificationBody: 'Die Panonischen Seen kosten heute nur 5 EUR statt 6 EUR!',
    close: 'Schliessen',
    viewOnMap: 'Auf der Karte ansehen',
    foundAt: 'Gefunden bei',
    liveEvents: 'Live-Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login mit OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Notfall-Infos',
    bestSupermarket: 'Bester Supermarkt',
    workingHours: 'Offnungszeiten',
    monSat: 'Mo - Sa',
    sunday: 'Sonntag',
    closed: 'Geschlossen',
    rating: 'Bewertung',
    reviews: 'Bewertungen',
    delivery: 'Lieferung moglich',
    noDelivery: 'Keine Lieferung',
    typicalPrice: 'Normaler Preis',
    arGuide: 'AR-Guide',
    walletManual: 'Bedienungsanleitung',
    howToConnect: 'So verbindest du dich',
    connectSteps: "1. Klick auf 'Connect Wallet'\n2. Wähle eine TON Wallet (Tonkeeper/Telegram) aus\n3. Bestätige alles in deiner App",
    safeUsage: 'Sicherheitstipps',
    safeTips: '. Teil niemals deine Recovery Phrase\n. Bestätige jede Transaktion einzeln\n. Nutze nur offizielle TON Apps',
    txHistory: 'Wo ist der Verlauf?',
    historyLocation: 'Dein Transaktionsverlauf wird direkt in deiner TON Wallet App gespeichert.',
    bamToEur: 'BAM - EUR Umrechner',
    enterBam: 'Betrag in BAM eingeben',
    calculatedEur: 'Gegenwert in EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Panonische Seen - Salzseen in Tuzla',
    pannonicaTitle: 'Willkommen an der Panonica',
    pannonicaImage: '/assets/PannonicaDE.webp',
    parkingTitle: 'Parken',
    parkingActive: 'Aktives Parkticket',
    parkingAutoDetect: 'Zone automatisch erkennen',
    parkingLicensePlate: 'Kennzeichen',
    parkingHourly: 'Stundlich',
    parkingDaily: 'Tagesticket',
    parkingPaySms: 'Per SMS bezahlen',
    parkingDetectNoZone: 'Keine Parkzone erkannt.',
    parkingPromptPlate: 'Zone bestatigen und Kennzeichen eingeben.',
    parkingPaymentInactive: 'Parkgebuhren sind gerade nicht aktiv.',
    parkingConfirm: 'Bestatigen',
    parkingCancel: 'Abbrechen',
    parkingDetected: 'Erkannt',
    trademarksDisclaimer: 'Alle Logos und Markennamen sind Eigentum ihrer jeweiligen Inhaber und werden hier nur zu Informations-/Identifikationszwecken verwendet.',
    privacyNoticeTitle: 'Datenschutz- und Kamerahinweis',
    privacyNoticeBody: 'Diese App verwendet Ihren Standort ausschliesslich zur Navigation zu Sehenswurdigkeiten. Die Kamera wird nur aktiviert, wenn Sie sich im Umkreis von 10m von einem Ziel befinden, um einen QR-Code zu scannen und den AR-Guide zu starten. Ihre Bilder und Video-Feeds werden weder gespeichert noch an Server gesendet; die gesamte Verarbeitung erfolgt ausschliesslich auf Ihrem Gerat. Mit der weiteren Nutzung stimmen Sie dem vorubergehenden Zugriff auf diese Funktionen zu.',
    learnMore: 'Mehr erfahren',
    busStation: 'Busbahnhof',
    batteryWarning: 'Extremer Energiesparmodus aktiv. Helligkeit senken und AR nur bei Bewegung nutzen.',
    selectNetwork: 'Netzwerk wählen',
    tonWallet: 'TON Wallet',
    switchNetwork: 'Netzwerk wechseln',
    connectedToTon: 'Mit TON verbunden',
    walletLocked: 'Wallet Gesperrt',
    setWalletPin: 'Wallet-PIN festlegen',
    confirmPin: 'PIN bestätigen',
    enterPin: 'PIN zum Entsperren eingeben',
    dentalTourism: 'Zahntourismus',
    parkingSearch: 'Parkplätze suchen...',
    locationNotAvailable: 'Standort nicht verfügbar.',
    zonesLabel: 'Zonen',
    galleryCharmText: 'Kein Foto kann Ihnen den Charme und die Schönheit dieser Stadt zeigen, also kommen Sie und besuchen Sie uns.',
  },
  tr: {
    welcome: 'Tuzla\'ya Hoşgeldiniz',
    history: 'Tarih',
    map: 'Harita',
    quest: 'Görev',
    gallery: 'Galeri',
    scanQr: 'QR Kodunu Tara',
    rewardClaimed: 'Ödül Açıldı!',
    discountMessage: 'Bir indirim kazandınız! Bunu kasada gösterin.',
    notificationTitle: 'Özel Teklif!',
    notificationBody: 'Pannonian Gölleri fiyatı bugün 6 EUR yerine 5 EUR!',
    close: 'Kapat',
    viewOnMap: 'Haritada Gör',
    foundAt: 'Bulundu',
    liveEvents: 'Canlı Etkinlikler ve Haberler',
    wallet: 'Cüzdan',
    loginOAuth: 'OAuth ile Giriş Yap',
    touristInfo: 'Turist Bilgisi',
    emergencyInfo: 'Acil Durum Bilgisi',
    bestSupermarket: 'Süpermarket',
    workingHours: 'Çalışma Saatleri',
    monSat: 'Pzt - Cmt',
    sunday: 'Pazar',
    closed: 'Kapalı',
    rating: 'Değerlendirme',
    reviews: 'Yorumlar',
    delivery: 'Teslimat Var',
    noDelivery: 'Teslimat Yok',
    typicalPrice: 'Tipik Fiyat',
    arGuide: 'AR Rehberi',
    walletManual: 'Kullanım Kılavuzu',
    howToConnect: 'Nasıl Bağlanılır',
    connectSteps: "1. 'Connect Wallet'a tıklayın\n2. TON cüzdanını (Tonkeeper/Telegram) seçin\n3. Uygulamada onaylayın",
    safeUsage: 'Güvenli Kullanım',
    safeTips: '. Şifrenizi asla paylaşmayın\n. Her işlemi onaylayın\n. Yalnızca resmi TON uygulamalarını kullanın',
    txHistory: 'Geçmiş nerede?',
    historyLocation: 'İşlem geçmişi bağlı TON cüzdanınıza kaydedilir.',
    bamToEur: 'BAM - EUR Çevrimi',
    enterBam: 'BAM miktarını girin',
    calculatedEur: 'EUR karşılığı',
    conversionRate: 'Kur: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Otopark',
    pannonicaAlt: 'Pannonica Gölleri - Tuzla\'daki Tuz Gölleri',
    pannonicaTitle: 'Pannonica\'ya Hoşgeldiniz',
    pannonicaImage: '/assets/Pannonica.webp',
    parkingTitle: 'Otopark',
    parkingActive: 'Aktif Otopark',
    parkingAutoDetect: 'Bölgemi Otomatik Algıla',
    parkingLicensePlate: 'Plaka',
    parkingHourly: 'Saatlik',
    parkingDaily: 'Günlük',
    parkingPaySms: 'SMS ile Öde',
    parkingDetectNoZone: 'Otopark bölgesi algılanmadı.',
    parkingPromptPlate: 'Bölgeyi onaylayın ve plakayı girin.',
    parkingPaymentInactive: 'Otopark ödemesi şu anda aktif değil.',
    parkingConfirm: 'Onayla',
    parkingCancel: 'İptal',
    parkingDetected: 'Algılandı',
    trademarksDisclaimer: 'Tüm logolar ve marka isimleri ilgili sahiplerinin mülkiyetindedir ve burada yalnızca bilgi/tanımlama amacıyla kullanılmıştır.',
    privacyNoticeTitle: 'Gizlilik ve Kamera Bildirimi',
    privacyNoticeBody: 'Bu uygulama konumunuzu yalnızca önemli noktalara navigasyon için kullanır. Kamera yalnızca bir hedefe 10m yaklaştığınızda QR kodunu taramak ve AR rehberini başlatmak için etkinleştirilir. Resimleriniz ve video akışınız kaydedilmez veya herhangi bir sunucuya gönderilmez; tüm işlemler yalnızca cihazınızda gerçekleşir. Devam ederek, bu işlevlere geçici erişime izin vermiş olursunuz.',
    learnMore: 'Daha Fazla Bilgi',
    busStation: 'Otobüs Durağı',
    batteryWarning: 'Ekstra Pil Tasarrufu Aktif. Güç tasarrufu için parlaklığı düşürün ve ARyı sadece hareket halindeyken kullanın.',
    selectNetwork: 'Ağ Seçin',
    tonWallet: 'TON Cüzdanı',
    switchNetwork: 'Ağı Değiştir',
    connectedToTon: 'TON\'a Bağlı',
    walletLocked: 'Cüzdan Kilitli',
    setWalletPin: 'Cüzdan PIN\'ini Ayarla',
    confirmPin: 'PIN\'i Onayla',
    enterPin: 'Kilidi Açmak İçin PIN Girin',
    dentalTourism: 'Diş Turizmi',
    parkingSearch: 'Otopark ara...',
    locationNotAvailable: 'Konum mevcut değil.',
    zonesLabel: 'Bölgeler',
    galleryCharmText: 'Hiçbir fotoğraf size bu şehrin cazibesini ve güzelliğini gösteremez, bu yüzden gelin ve bizi ziyaret edin.',
  },
};

const RESTAURANTS_RAW = [
  {
    name: 'Taco Bell',
    address: 'Univerzitetska 16 (Tuzlanka Mall)',
    type: { en: 'Mexican Fast Food', bs: 'Meksicka brza hrana', de: 'Mexikanisches Fast Food', tr: 'Meksika Fast Food' },
    price: '9-18 KM',
    image: '/assets/Gallery/Food/taco.webp',
  },
  {
    name: 'Pekara Hukic',
    address: 'Gradska 59, Tuzla',
    type: { en: 'Traditional Bakery & Pizza', bs: 'Tradicionalna pekara i pizza', de: 'Traditionelle Backerei & Pizza', tr: 'Geleneksel Fırın ve Pizza' },
    price: '3-17 KM',
    image: '/assets/Gallery/Food/huka.webp',
  },
  {
    name: 'Bagi Palačinkara',
    address: 'Patriotske lige 10, Tuzla',
    type: { en: 'Famous Sweet & Sushi Pancakes', bs: 'Poznate slatke i sushi palacinke', de: 'Legendare suse Pfannkuchen & Pancake-Sushi', tr: 'Ünlü Tatlı ve Suşi Krepleri' },
    price: '3-9 KM',
    image: '/assets/Gallery/Food/bagi.webp',
  },
  {
    name: 'Libero Caffe',
    address: 'Armije Republike BiH 17, Tuzla',
    type: { en: 'Vibrant Social Hub & Italian Food', bs: 'Popularni caffe i italijanska hrana', de: 'Vibranter Social Hub & italienisches Essen', tr: 'Canlı Sosyal Merkez ve İtalyan Yemekleri' },
    price: '7-15 KM',
    image: '/assets/Gallery/Food/libero.webp',
  },
  {
    name: 'Choco Loco',
    address: 'Solni trg / Prekinute mladosti 10, Tuzla',
    type: { en: 'Rich Cakes & Turkish Lokma', bs: 'Bogati kolaci i turske lokme', de: 'Kuchen & Lokma', tr: 'Zengin Pastalar ve Türk Lokması' },
    price: '3-7 KM',
    image: '/assets/Gallery/Food/chocoloco.webp',
  },
  {
    name: 'Nota Bene Pizzeria',
    address: 'I inzinjerske brigade, Tuzla',
    type: { en: 'Quality Italian Pizza & Breakfast', bs: 'Kvalitetna italijanska pizza i dorucak', de: 'Italienische Pizza & Fruhstuck', tr: 'Kaliteli İtalyan Pizzası ve Kahvaltı' },
    price: '6-10 KM',
    image: '/assets/Gallery/Food/notabene.webp',
  },
  {
    name: 'Restaurant Saranda',
    address: 'Maršala Tita 88, Tuzla',
    type: { en: 'Traditional Restaurant', bs: 'Tradicionalni restoran', de: 'Traditionelles Restaurant', tr: 'Geleneksel Restoran' },
    price: '10-25 KM',
    image: '/assets/Gallery/Food/saranda.webp',
  },
  {
    name: 'Pizza Trkačica',
    address: 'Nesiba Malkića 20, Tuzla',
    type: { en: 'Pizza & Delivery', bs: 'Pizza i dostava', de: 'Pizza & Lieferservice', tr: 'Pizza ve Teslimat' },
    price: '6-18 KM',
    image: '/assets/Gallery/Food/trkacica.webp',
  },
  {
    name: 'Mamma Mia Origins',
    address: 'Trg slobode bb, Tuzla',
    type: { en: 'Steak & Wine / Upscale', bs: 'Steak & Wine / Elitno', de: 'Steak & Wein / Gehoben', tr: 'Biftek ve Şarap / Lüks' },
    price: '20-60 KM',
    image: '/assets/Gallery/Food/mia.webp',
  },
  {
    name: 'Papi Gelato',
    address: 'Hadžihasanage Pašića 3, Tuzla',
    type: { en: 'Artisanal Gelato', bs: 'Artisan sladoled', de: 'Hausgemachtes Eis', tr: 'Zanaat Dondurması' },
    price: '3-10 KM',
    image: '/assets/Gallery/Food/papi.webp',
  },
  {
    name: 'Restaurant Sedra',
    address: 'Slatina 5, Tuzla',
    type: { en: 'Traditional Dining', bs: 'Tradicionalna kuhinja', de: 'Traditionelle Küche', tr: 'Geleneksel Mutfak' },
    price: '8-22 KM',
    image: '/assets/Gallery/Food/sedra.webp',
  },
  {
    name: 'Alibaba Restoran',
    address: 'Toplice 1, Tuzla',
    type: { en: 'Traditional Atmosphere', bs: 'Tradicionalni ambijent', de: 'Traditionelles Ambiente', tr: 'Geleneksel Atmosfer' },
    price: '7-20 KM',
    image: '/assets/Gallery/Food/alibaba.webp',
  },
  {
    name: 'Gradska Kafana',
    address: 'ZAVNOBiH-a 13, Tuzla',
    type: { en: 'Classic Café', bs: 'Klasična kafana', de: 'Klassisches Café', tr: 'Klasik Kafe' },
    price: '2-8 KM',
    image: '/assets/Gallery/Food/kafana.webp',
  },
  {
    name: 'Čevabdžinica Limenka',
    address: 'Patriotske lige 24, Tuzla',
    type: { en: 'Iconic Ćevapi Spot', bs: 'Kultna ćevabdžinica', de: 'Kult-Ćevapi-Laden', tr: 'İkonik Köfteci' },
    price: '5-12 KM',
    image: '/assets/Gallery/Food/limenka.webp',
  },
  {
    name: 'Mozaik',
    address: 'Turalibegova 2, Tuzla',
    type: { en: 'International Restaurant', bs: 'Internacionalni restoran', de: 'Internationales Restaurant', tr: 'Uluslararası Restoran' },
    price: '10-30 KM',
    image: '/assets/Gallery/Food/mozaik.webp',
  },
  {
    name: 'Fast Food King',
    address: 'Trzni Centar, Tuzla',
    type: { en: 'Burgers & Fries', bs: 'Burgeri i pomfrit', de: 'Burger & Pommes', tr: 'Burger ve Patates' },
    price: '5-15 KM',
    image: '/assets/Gallery/Food/king.webp',
  },
  {
    name: 'Sezam Tennis',
    address: 'Nesiba Malkica 20, Tuzla',
    type: { en: 'Pizza & Grill', bs: 'Pizza i roštilj', de: 'Pizza & Grill', tr: 'Pizza ve Izgara' },
    price: '7-20 KM',
    image: '/assets/Gallery/Food/foodprime.webp',
  },
  {
    name: 'Pizzeria La Linea',
    address: 'Stupine B2, Tuzla',
    type: { en: 'Pizza & Pasta', bs: 'Pizza i pasta', de: 'Pizza & Pasta', tr: 'Pizza ve Makarna' },
    price: '6-18 KM',
    image: '/assets/Gallery/Food/lineaaa.webp',
  },
  {
    name: 'Ćevabdžinica Brajlović',
    address: 'Gradska ulica, Tuzla',
    type: { en: 'Traditional Ćevapi', bs: 'Tradicionalni ćevapi', de: 'Traditionelle Ćevapi', tr: 'Geleneksel Köfte' },
    price: '7-15 KM',
    image: '/assets/Gallery/Food/cevapibrajlovic.webp'
  },
  {
    name: 'Smash Bos Burger',
    address: 'Univerzitetska 16, Tuzla',
    type: { en: 'Modern Smash Burgers', bs: 'Moderni smash burgeri', de: 'Moderne Smash Burger', tr: 'Modern Smash Burgerler' },
    price: '8-16 KM',
    image: '/assets/Gallery/Food/smashbosbur.webp'
  },
  {
    name: 'Restoran Bosna',
    address: 'Bosne Srebrene, Tuzla',
    type: { en: 'Traditional Bosnian Food', bs: 'Tradicionalna bosanska hrana', de: 'Traditionelles bosnisches Essen', tr: 'Geleneksel Boşnak Yemeği' },
    price: '10-30 KM',
    image: '/assets/Gallery/Food/bosna.webp'
  },
];

export const TUZLA_DINING_DATA: LocationData[] = [
  {
    name: 'Taco Bell Tuzla',
    rating: 4.3,
    user_ratings_total: 189,
    address: 'Univerzitetska 16, Tuzla',
    latitude: 44.538497,
    longitude: 18.664660,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/taco.webp',
  },
  {
    name: 'Pekara Hukic',
    rating: 4.6,
    user_ratings_total: 410,
    address: 'ZAVNOBiH-a 7, Tuzla',
    latitude: 44.539990,
    longitude: 18.673059,
    category: 'Bakery',
    type: 'Dining',
    image: '/assets/Gallery/Food/huka.webp',
  },
  {
    name: 'Libero Caffe',
    rating: 4.5,
    user_ratings_total: 278,
    address: 'Armije Republike Bosne i Hercegovine 17, Tuzla',
    latitude: 44.542283,
    longitude: 18.693450,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/libero.webp',
  },
  {
    name: 'Nota Bene Pizzeria',
    rating: 4.8,
    user_ratings_total: 320,
    address: 'I inzinjerske brigade bb, Tuzla',
    latitude: 44.534160,
    longitude: 18.698330,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/notabene.webp',
  },
  {
    name: 'Mozaik',
    rating: 4.7,
    user_ratings_total: 493,
    address: 'Turalibegova 2, Tuzla',
    latitude: 44.537233,
    longitude: 18.674936,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/mozaik.webp',
  },
  {
    name: 'Pizza Trkačica',
    rating: 4.9,
    user_ratings_total: 211,
    address: 'Nesiba Malkića 20, Tuzla',
    latitude: 44.525767,
    longitude: 18.696539,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/trkacica.webp',
    website: 'http://trkacica.com/'
  },
  {
    name: 'Fast Food King',
    rating: 4.9,
    user_ratings_total: 257,
    address: 'GMMW+9R6 Trzni Centar, Tuzla',
    latitude: 44.53721,
    longitude: 18.67817,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/king.webp',
  },
  {
    name: 'Sezam Tennis',
    rating: 4.9,
    user_ratings_total: 59,
    address: 'Nesiba Malkica 20, Tuzla',
    latitude: 44.538717,
    longitude: 18.676906,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/foodprime.webp',
  },
  {
    name: 'Pizzeria La Linea',
    rating: 4.9,
    user_ratings_total: 47,
    address: 'Stupine B2, Tuzla',
    latitude: 44.531200,
    longitude: 18.688800,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/lineaaa.webp',
  },
  {
    name: 'Restaurant Saranda',
    rating: 4.4,
    user_ratings_total: 245,
    address: 'Maršala Tita 88, Tuzla',
    latitude: 44.5343,
    longitude: 18.6944,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/saranda.webp',
    website: 'http://www.saranda.ba/'
  },
  {
    name: 'Mama Mia Origins',
    rating: 4.7,
    user_ratings_total: 156,
    address: 'Trg slobode bb, Tuzla',
    latitude: 44.5388,
    longitude: 18.6755,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/mia.webp',
    website: 'https://mamamiaorigins.com/'
  },
  {
    name: 'Papi Gelato',
    rating: 4.8,
    user_ratings_total: 312,
    address: 'Hadžihasanage Pašića 3, Tuzla',
    latitude: 44.5386,
    longitude: 18.6753,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/papi.webp'
  },
  {
    name: 'Restaurant Sedra',
    rating: 4.4,
    user_ratings_total: 189,
    address: 'Slatina 5, Tuzla',
    latitude: 44.5375,
    longitude: 18.6630,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/sedra.webp',
    website: 'https://sedra.ba/'
  },
  {
    name: 'Alibaba Restoran',
    rating: 4.5,
    user_ratings_total: 124,
    address: 'Toplice 1, Tuzla',
    latitude: 44.5370,
    longitude: 18.6780,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/alibaba.webp'
  },
  {
    name: 'Gradska Kafana',
    rating: 4.3,
    user_ratings_total: 278,
    address: 'ZAVNOBiH-a 13, Tuzla',
    latitude: 44.5390,
    longitude: 18.6750,
    category: 'Café',
    type: 'Dining',
    image: '/assets/Gallery/Food/kafana.webp'
  },
  {
    name: 'Čevabdžinica Limenka',
    rating: 4.7,
    user_ratings_total: 540,
    address: 'Patriotske lige 24, Tuzla',
    latitude: 44.5394,
    longitude: 18.6825,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/limenka.webp',
    website: 'http://www.limenka.ba/'
  },
  {
    name: 'Bagi Palačinkara',
    rating: 4.9,
    user_ratings_total: 856,
    address: 'Patriotske lige 10, Tuzla',
    latitude: 44.5392,
    longitude: 18.6755,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/bagi.webp'
  },
  {
    name: 'Choco Loco',
    rating: 4.8,
    user_ratings_total: 420,
    address: 'Prekinute mladosti 10, Tuzla',
    latitude: 44.5385,
    longitude: 18.6738,
    category: 'Dessert',
    type: 'Dining',
    image: '/assets/Gallery/Food/chocoloco.webp'
  },
  {
    name: 'Ćevabdžinica Brajlović',
    rating: 4.7,
    user_ratings_total: 124,
    address: 'Gradska ulica, Tuzla',
    latitude: 44.5389,
    longitude: 18.6815,
    category: 'Traditional',
    type: 'Dining',
    image: '/assets/Gallery/Food/cevapibrajlovic.webp'
  },
  {
    name: 'Smash Bos Burger',
    rating: 4.8,
    user_ratings_total: 98,
    address: 'Univerzitetska 16, Tuzla',
    latitude: 44.5383,
    longitude: 18.6652,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/smashbosbur.webp'
  },
  {
    name: 'Restoran Bosna',
    rating: 4.6,
    user_ratings_total: 156,
    address: 'Bosne Srebrene, Tuzla',
    latitude: 44.5380,
    longitude: 18.6740,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/bosna.webp'
  },
];

export const ALL_TUZLA_VENUES = TUZLA_DINING_DATA;

export const LOCATIONS = LOCATIONS_RAW;
export const BINGO_STORE = BINGO_STORE_RAW;
export const TRANSLATIONS: Record<Language, TranslationSet> = TRANSLATIONS_RAW;
export const RESTAURANTS = RESTAURANTS_RAW;

export const TUZLA_PARKING_DATA: ParkingLot[] = [
  {
    id: "bcc-main",
    name: "Bingo City Center",
    area: "Parking Centar",
    address: "Mitra Trifunovića Uče 2",
    coordinates: [18.653272, 44.532753],
    features: ["Shopping mall access", "Surface parking"]
  },
  {
    id: "bcc-garage",
    name: "Bingo City Center - Parking Garaža",
    area: "Zapad / Miladije",
    address: "Mitra Trifunovića Uče 2",
    coordinates: [18.650794, 44.532072],
    features: ["Underground garage", "EV Charging (15 kW)", "First 2 hours free"]
  },
  {
    id: "skver",
    name: "Skver parking - Kojšino",
    area: "Skver/Kojšino",
    address: "Mije Keroševića Guje 24",
    coordinates: [18.673362, 44.540963],
    features: ["Open surface lot", "24/7 access"]
  },
  {
    id: "omega-tuzlanka",
    name: "Parking Omega (TC Tuzlanka)",
    area: "Parking Omega",
    address: "Univerzitetska",
    coordinates: [18.663186, 44.538282],
    features: ["No Charge", "Commercial surface lot", "Short-term validation"]
  },
  {
    id: "slatina-main",
    name: "Gradski Parking Slatina",
    area: "Slatina",
    address: "Alana Forda (Behind Health Center)",
    coordinates: [18.667944, 44.540657],
    features: ["Zone 1", "Public lot", "Close to Dom Zdravlja clinic"]
  },
  {
    id: "slatina",
    name: "SodaSo Parking Slatina",
    area: "Slatina",
    address: "Slatina, Tuzla",
    coordinates: [18.665482, 44.540615],
    features: ["Zone 1", "Public lot", "Parking Slatina"]
  },
  {
    id: "gradski-kulina-bana",
    name: "Gradski Parking Centar",
    area: "Centar",
    address: "Kulina bana 8",
    coordinates: [18.675910, 44.539877],
    features: ["Municipal managed", "Zone 0", "Near pedestrian walk"]
  },
  {
    id: "turalibegova",
    name: "Parking Turalibegova",
    area: "Centar",
    address: "Turalibegova 59",
    coordinates: [18.6792208, 44.536256],
    features: ["Automated ticketing", "High-turnover commercial area"]
  },
  {
    id: "cipelici",
    name: "Parking Čipelići",
    area: "Centar / Čipelići",
    address: "Junction of Turalibegova & Klosterska",
    coordinates: [18.680749, 44.535120],
    features: ["Zone 1 dynamic pricing", "Automated entry ramp"]
  },
  {
    id: "pannonica-west",
    name: "Parkiralište Jezero Zapad",
    area: "Pannonica",
    address: "Džindić mahala",
    coordinates: [18.67687, 44.540775],
    features: ["JKP Saobraćaj i komunikacije", "Direct lake gate entry"]
  },
  {
    id: "kajmak-stanica",
    name: "Parking Kajmak Stanica",
    area: "Centar / Sjever",
    address: "Kulina bana (Old bus station layout)",
    coordinates: [18.681108, 44.538007],
    features: ["Automated ramp gates", "High capacity (~200 spaces)"]
  },
  {
    id: "pannonica-east",
    name: "Parking Pannonica Istok",
    area: "Pannonica",
    address: "Ulica Džamala Bijedića area",
    coordinates: [18.683013, 44.538279],
    features: ["Large surface capacity", "Automated pay terminals"]
  },
  {
    id: "gradina-hospital",
    name: "Parking Gradina (UKC Tuzla)",
    area: "Gradina",
    address: "Put Gradina",
    coordinates: [18.691902, 44.537556],
    features: ["Independent medical campus tariff", "Incline surface terrain"]
  },
  {
    id: "mellain-complex",
    name: "Mellain Garaža",
    area: "Centar / Istok",
    address: "Aleja Alije Izetbegovića 3",
    coordinates: [18.687208, 44.533881],
    features: ["Multi-level underground", "24/7 security & video"]
  },
  {
    id: "stupine-main",
    name: "Parking Stupine",
    area: "Stupine",
    address: "Mehmedalije Maka Dizdara",
    coordinates: [18.691612, 44.529851],
    features: ["Zone 1 public parking", "Open-air surface spaces"]
  },
  {
    id: "15-maja",
    name: "Parking 15. maja",
    area: "Brčanska Malta",
    address: "15. maja 2",
    coordinates: [18.697177, 44.530279],
    features: ["Broad parking bays", "Low congestion area"]
  },
  {
    id: "bulevar-BHTelecom",
    name: "Parking BHTelecom",
    area: "bhtelecom",
    address: "Bulevar 2. korpusa",
    coordinates: [18.691429, 44.533269],
    features: ["zone 1 payment 1.00KM/h, 5.00KM/day"]
  },
  {
    id: "sjenjak-fringes",
    name: "Parking Sjenjak Zapad",
    area: "Sjenjak",
    address: "Ismeta Mujezinovica B-blok",
    coordinates: [18.699787, 44.533239],
    features: ["No Charge", "Open public bay", "Feeder lanes to high-rise zones"]
  },
  {
    id: "sjenjak-main",
    name: "Gradski Parking Sjenjak",
    area: "Sjenjak",
    address: "GMMX+3CH block",
    coordinates: [18.699862, 44.532244],
    features: ["No Charge", "Large neighborhood lot", "Easy connection to eastern bypass"]
  }
];

export const TUZLA_WIFI_DATA: WifiSpot[] = [
  {
    id: "wifi-trg-slobode",
    name: {
      en: "Free WiFi - Freedom Square",
      bs: "Besplatan WiFi - Trg Slobode",
      de: "Kostenloses WLAN - Freiheitsplatz",
      tr: "Ücretsiz WiFi - Özgürlük Meydanı"
    },
    description: {
      en: "High-speed public WiFi available throughout Freedom Square. Provided by the City of Tuzla.",
      bs: "Brzi javni WiFi dostupan na cijelom području Trga Slobode. Obezbjeđuje Grad Tuzla.",
      de: "Schnelles öffentliches WLAN auf dem gesamten Freiheitsplatz. Bereitgestellt von der Stadt Tuzla.",
      tr: "Özgürlük Meydanı genelinde yüksek hızlı ücretsiz kamu WiFi. Tuzla Belediyesi tarafından sağlanmaktadır."
    },
    latitude: 44.53956,
    longitude: 18.67570,
    ssid: "Tuzla_Free_WiFi"
  },
  {
    id: "wifi-panonika",
    name: {
      en: "Free WiFi - Pannonian Lakes",
      bs: "Besplatan WiFi - Panonska Jezera",
      de: "Kostenloses WLAN - Pannonische Seen",
      tr: "Ücretsiz WiFi - Pannonian Gölleri"
    },
    description: {
      en: "Free WiFi coverage near the main entrance and first lake area. Active during summer season.",
      bs: "Besplatan WiFi signal u blizini glavnog ulaza i prvog jezera. Aktivno tokom ljetne sezone.",
      de: "Kostenloser WLAN-Empfang in der Nähe des Haupteingangs und des ersten Sees. Aktiv während der Sommersaison.",
      tr: "Ana giriş ve ilk göl bölgesi yakınında ücretsiz WiFi kapsama alanı. Yaz sezonu boyunca aktiftir."
    },
    latitude: 44.53880,
    longitude: 18.68005,
    ssid: "Panonika_Guest"
  },
  {
    id: "wifi-slana-banja",
    name: {
      en: "Free WiFi - Slana Banja Park",
      bs: "Besplatan WiFi - Slana Banja",
      de: "Kostenloses WLAN - Slana Banja Park",
      tr: "Ücretsiz WiFi - Slana Banja Parkı"
    },
    description: {
      en: "Free public WiFi coverage around the central memorial area of Slana Banja Park.",
      bs: "Besplatan javni WiFi signal oko centralnog spomen-obilježja u parku Slana Banja.",
      de: "Kostenloses öffentliches WLAN rund um den zentralen Gedenkbereich des Slana Banja Parks.",
      tr: "Slana Banja Parkı'nın merkezi anıt alanı çevresinde ücretsiz kamu WiFi."
    },
    latitude: 44.53820,
    longitude: 18.68540,
    ssid: "Slana_Banja_Free"
  },
  {
    id: "wifi-soni-trg",
    name: {
      en: "Free WiFi - Salt Square",
      bs: "Besplatan WiFi - Soni Trg",
      de: "Kostenloses WLAN - Salzplatz",
      tr: "Ücretsiz WiFi - Tuz Meydanı"
    },
    description: {
      en: "Free municipal WiFi network surrounding the historic Salt Square.",
      bs: "Besplatna gradska WiFi mreža na prostoru istorijskog Sonog Trga.",
      de: "Kostenloses städtisches WLAN-Netzwerk rund um den historischen Salzplatz.",
      tr: "Tarihi Tuz Meydanı'nı çevreleyen ücretsiz belediye WiFi ağı."
    },
    latitude: 44.53877,
    longitude: 18.67305,
    ssid: "Grad_Tuzla_WiFi"
  },
  {
    id: "wifi-bcc",
    name: {
      en: "Free WiFi - Bingo City Center",
      bs: "Besplatan WiFi - Bingo City Center",
      de: "Kostenloses WLAN - Bingo City Center",
      tr: "Ücretsiz WiFi - Bingo City Center"
    },
    description: {
      en: "High-speed mall WiFi available for all visitors. Connect and browse instantly.",
      bs: "Brzi WiFi tržnog centra dostupan za sve posjetioce. Povežite se i surfajte odmah.",
      de: "Schnelles WLAN im Einkaufszentrum für alle Besucher. Sofort verbinden und surfen.",
      tr: "Tüm ziyaretçiler için yüksek hızlı alışveriş merkezi WiFi. Anında bağlanın ve göz atın."
    },
    latitude: 44.53185,
    longitude: 18.65215,
    ssid: "BCC_FREE_WIFI"
  }
];

